project:
  type: book
  output-dir: docs


date-format: iso
institute: "Wilfrid Laurier University"
number-depth: 2
author: "Dr. Devan Becker"

book:
  title: "Course Notes for ST231"
  subtitle: "Introduction to Statistics for the Life Sciences"
  author: "Dr. Devan Becker"
  date: "6/20/2023"
  repo-url: https://github.com/DB7-CourseNotes/ST231_S23
  repo-actions: [issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: Pre-Midterm
      chapters:
        - L01-Intro_PicturingGraphs.qmd
        - L02-Describing_Distributions_Numbers.qmd
        - L03-Scatterplots_Correlation.qmd
        - L04-Regression.qmd
        - L05-Probability.qmd
        - L07-Normal_Distributions.qmd
        - L09-Binomial_Probabilities.qmd
        - L10-Sampling_Distributions.qmd
    - part: Post-Midterm
      chapters:
        - L12-Intro_to_Inference-CI-pvals.qmd
        - L13-p_vals.qmd
        - L14-Inference_Cautions.qmd
        - L15-CI_for_Means.qmd
        - L16-Hypothesis_Tests_for_Means.qmd
        - L17-Two_Sample_hypothesis_Tests.qmd
        - L18-Hypothesis_Tests_for_Proportions.qmd
        - L19-CI_for_Proportions.qmd
        - L19-Summary_of_Inference-Means_Proportions.qmd

execute: 
  warning: false

format:
  html:
    theme:
      light: flatly
      dark: darkly
    mainfont: ubuntu, sans-serif
    execute:
        code-fold: true
        code-summary: "Show the code"
        warning: false
  pdf:
    include-in-header: defs_pdf.tex



