project:
  type: book
  output-dir: ../docs


date-format: iso
institute: "Wilfrid Laurier University"
number-depth: 2
author: "Dr. Devan Becker"

book:
  title: "Course Notes for ST231"
  author: "Dr. Devan Becker"
  date: "6/20/2023"
  repo-url: https://github.com/DB7-CourseNotes/ST231_S23
  repo-actions: [edit]
  chapters:
    - index.qmd
    - part: Pre-Midterm
      chapters:
        - CourseNotes/L01-Intro_PicturingGraphs.qmd
        - CourseNotes/L02-Describing_Distributions_Numbers.qmd
        - CourseNotes/L03-Scatterplots_Correlation.qmd
        - CourseNotes/L04-Regression.qmd
        - CourseNotes/L05-Probability.qmd
        - CourseNotes/L07-Normal_Distributions.qmd
        - CourseNotes/L09-Binomial_Probabilities.qmd
        - CourseNotes/L10-Sampling_Distributions.qmd
    - part: Post-Midterm
      chapters:
        - CourseNotes/L12-Intro_to_Inference-CI-pvals.qmd
        - CourseNotes/L13-p_vals.qmd
        - CourseNotes/L14-tCI.qmd

execute: 
  warning: false

format:
  html:
    theme:
      light: pulse
      dark: cyborg
    execute:
        echo: false
        warning: false



