project:
  type: book
  output-dir: docs


date-format: iso
number-depth: 2
author: "Dr. Devan Becker"
date: last-modified

book:
  title: "Statistics for Life Sciences"
  subtitle: "Course Notes for ST231, Updated for Winter 2024"
  author: "Dr. Devan Becker"
  date: "6/20/2023"
  repo-url: https://github.com/DB7-CourseNotes/ST231
  repo-actions: [issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: Pre-Midterm
      chapters:
        - L01-Intro_PicturingGraphs.qmd
        - L02-Describing_Distributions_Numbers.qmd
        - L03-Scatterplots_Correlation.qmd
        - L04-Regression.qmd
        - L05-Probability.qmd
        - L07-Binomial_Probabilities.qmd
        - L08-Normal_Distributions.qmd
        - L10-Sampling_Distributions.qmd
    - part: Post-Midterm
      chapters:
        - L12-Intro_to_Inference-CI-pvals.qmd
        - L13-p_vals.qmd
        - L14-Inference_Cautions.qmd
        - L15-CI_for_Means.qmd
        - L16-Hypothesis_Tests_for_Means.qmd
        - L17-Two_Sample_hypothesis_Tests.qmd
        - L18-Hypothesis_Tests_for_Proportions.qmd
        - L19-CI_for_Proportions.qmd
        - L20-Two_Proportions.qmd
        - L21-ChiSquare_Multiple_Proportions.qmd
        - L22-Inference_for_Regression.qmd
        - L23-ANOVA-oi.qmd
        - L24-Review.qmd

execute: 
  warning: false

format:
  html:
    theme:
      light: [flatly, smaller_lists.scss]
      dark: [darkly, smaller_lists.scss]
    mainfont: ubuntu, sans-serif
    execute:
        code-fold: true
        code-summary: "Show the code"
        warning: false



