---
title: "Large sample test for a proportion"
author: "Devan Becker"
date: "21/07/2020"
output: 
  word_document:
    toc: yes
  pdf_document:
    toc: yes
  tufte::tufte_html:
    css: my_tufte.css
    number_sections: yes
    toc: yes
    tufte_variant: envisioned
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Refresher

In the lecture on sampling distributions, we learned that the sampling distribution of a sample proportion can be found as follows:

If $X\sim B(n,p)$ and $np>10$ and $n(1-p)>10$, then
$$
\hat p \sim N\left(p, \sqrt{\frac{p(1-p)}{n}}\right)
$$

This relies on the population proportion to find the standard error, but this is never available.^[f it was, then why are we doing inference?] The standard error can be estimated and used in the sampling distribution:
$$
\hat p \sim N\left(p, \sqrt{\frac{\hat p(1-\hat p)}{n}}\right)
$$

I said that this would be the last time I change the standard error. I will now make a liar out of myself.


# Hypothesis tests for proportions


As before, we write our hypotheses:
$$
H_0:p = p_0 \text{ vs. } H_A: p \{>or<or\ne\} p_0
$$

We always write $H_0:p = $ and then fill in the value for $p_0$, then we use that same value in the alternate hypothesis but use either $>$, $<$, or $\ne$ based on the wording of the question.

As before, we use the sampling distribution to find our p-value. In this case, though, we have a hypothesized value for the population proportion. In fact, we *must* assume that the null is true.^[We want to be strict about this so that it's more convincing if we prove it wrong.] If this is the case, we *have* the standard error!

I swear, this is the last time I introduce a new standard error for the sampling distribution of the sample proportion. Assuming $H_0$ is true (and the conditions are met),
$$
\hat p \sim N\left(p_0, \sqrt{\frac{p_0(1-p_0)}{n}}\right)
$$


## The Test Statistic

As you can guess from the sampling distribution, the test statistic is:

$$
z_{obs} = \frac{\hat p - p_0}{\sqrt{p_0(1-p_0)/n}}
$$

and then we can use the normal distribution as usual:
$$
P(Z \{>or<or\text{ further away than}\} z_{obs}) = \dots
$$

where we use $>$ if the alternate hypothesis uses $>$, $<$ if the alternate hypothesis uses $<$, and we look at the two tails if the alternate hypothesis is $\ne$. 

A common question is: which $p$ do we use to check normality? 

For a hypothesis test, we assume the null is true, i.e. $p=p_0$. We should use this assumption *everywhere*! For a hypothesis test about a proportion, we check whether $np_0>10$ and $n(1-p_0)>10$^[As before, both conditions must be true.].



# Example

## Mendelian Genetics 

To test his theory that 75% of plants would inheret a dominant gene, Gregor Mendel cross bred pure breeds of pea plants. Out of 7324 plants, 5474 showed the dominant trait. At the 4.5% level, is this compatible with the hypothesis of 75% dominant?

**Solution:**

1. Check: $np_0 = 7324*0.75 > 10$ and $n(1-p_0) = 7324*0.25 > 10$.
2. $z_{obs} = \frac{\hat p - p_0}{\sqrt{p_0(1-p_0)/n}} = \frac{0.747 - 0.75}{\sqrt{0.75*0.25/7324}} = -0.513$
3. $p-val = 2 *P(Z < z_{obs})$ = `2*pnorm(-0.513)` = 0.608
    - We doubled the $P(Z < z_{obs})$ because we want both tails. If you do this and your p-value is larger than 1, do $1 - P(Z < z_{obs})$ first and then double it.
4. Conclusion: Since $p-val > \alpha$, we do not reject the null. The hypothesis that 75% of plants inherent the dominant trait is compatible with the data.

The last step is important: always word your conclusion in the context of the study.

## Mendelian Genetics Part 2

Recall from last lecture the duality of the CI and the hypothesis test. For this question, a 95.5\%^[$\alpha = 0.045$, so $1 - \alpha = 0.955$.] CI can be found as:
$$
\hat p \pm z^*\sqrt{\frac{\hat p(1-\hat p)}{n}} = 0.747 \pm 2.005\sqrt{\frac{0.747(1-0.747)}{7324}}
$$

which results in the CI (0.737, 0.758).

Note that $\hat p$ was used in the SE since the CI is not based on a hypothesis. For proportions, it is not true that the CI contains all hypotheses that would not be rejected because the CI and the hypothesis test use different standard errors. 


# Self-Study Questions

1. When do we use $\hat p$ in the standard error? When do we use $p_0$?
2. Explain why we don't estimate the standard error in a hypothesis test about a proportion.



























