<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.333">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Devan Becker">
<meta name="dcterms.date" content="2023-05-08">

<title>Course Notes for ST231 - 1&nbsp; Picturing Distributions with Graphs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./L02-Describing_Distributions_Numbers.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./L01-Intro_PicturingGraphs.html">Pre-Midterm</a></li><li class="breadcrumb-item"><a href="./L01-Intro_PicturingGraphs.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Picturing Distributions with Graphs</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Course Notes for ST231</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/DB7-CourseNotes/ST231_S23" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Pre-Midterm</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L01-Intro_PicturingGraphs.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Picturing Distributions with Graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L02-Describing_Distributions_Numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions with Numbers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L03-Scatterplots_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Scatterplots and Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L04-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L05-Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability Background</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L07-Normal_Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Normal Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L09-Binomial_Probabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Binomial Probabilities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L10-Sampling_Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Post-Midterm</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L12-Intro_to_Inference-CI-pvals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Welcome to Inference!</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L13-p_vals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Tests of Significance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L14-tCI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Confidence Intervals (without the Silliness)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#defining-statistics" id="toc-defining-statistics" class="nav-link" data-scroll-target="#defining-statistics">Defining “Statistics”</a></li>
  <li><a href="#why-study-variance" id="toc-why-study-variance" class="nav-link" data-scroll-target="#why-study-variance">Why study variance?</a></li>
  <li><a href="#descriptive-versus-inferential-statistics" id="toc-descriptive-versus-inferential-statistics" class="nav-link" data-scroll-target="#descriptive-versus-inferential-statistics">Descriptive Versus Inferential Statistics</a></li>
  </ul></li>
  <li><a href="#descriptive-statistics-plots-and-graphs" id="toc-descriptive-statistics-plots-and-graphs" class="nav-link" data-scroll-target="#descriptive-statistics-plots-and-graphs"><span class="header-section-number">1.2</span> Descriptive Statistics: Plots and Graphs</a>
  <ul class="collapse">
  <li><a href="#the-palmer-penguins-data" id="toc-the-palmer-penguins-data" class="nav-link" data-scroll-target="#the-palmer-penguins-data">The Palmer Penguins Data</a></li>
  <li><a href="#types-of-variables" id="toc-types-of-variables" class="nav-link" data-scroll-target="#types-of-variables">Types of Variables</a></li>
  <li><a href="#grey-areas" id="toc-grey-areas" class="nav-link" data-scroll-target="#grey-areas">Grey Areas</a></li>
  <li><a href="#individuals-subjects" id="toc-individuals-subjects" class="nav-link" data-scroll-target="#individuals-subjects">Individuals (Subjects)</a></li>
  <li><a href="#example-what-are-the-individuals-what-are-variables" id="toc-example-what-are-the-individuals-what-are-variables" class="nav-link" data-scroll-target="#example-what-are-the-individuals-what-are-variables">Example: What are the Individuals? What are Variables?</a></li>
  </ul></li>
  <li><a href="#graphs" id="toc-graphs" class="nav-link" data-scroll-target="#graphs"><span class="header-section-number">1.3</span> Graphs</a>
  <ul class="collapse">
  <li><a href="#words-are-hard" id="toc-words-are-hard" class="nav-link" data-scroll-target="#words-are-hard">Words are Hard</a></li>
  <li><a href="#pie-charts" id="toc-pie-charts" class="nav-link" data-scroll-target="#pie-charts">Pie Charts</a></li>
  <li><a href="#bar-charts-categories" id="toc-bar-charts-categories" class="nav-link" data-scroll-target="#bar-charts-categories">Bar Charts: Categories</a></li>
  <li><a href="#quantitative-variables" id="toc-quantitative-variables" class="nav-link" data-scroll-target="#quantitative-variables">Quantitative Variables</a></li>
  <li><a href="#quantitative-variables-1" id="toc-quantitative-variables-1" class="nav-link" data-scroll-target="#quantitative-variables-1">Quantitative Variables</a></li>
  <li><a href="#quantitative-variables-as-a-bar-chart" id="toc-quantitative-variables-as-a-bar-chart" class="nav-link" data-scroll-target="#quantitative-variables-as-a-bar-chart">Quantitative Variables as a Bar Chart</a></li>
  <li><a href="#histograms-put-observations-into-bins" id="toc-histograms-put-observations-into-bins" class="nav-link" data-scroll-target="#histograms-put-observations-into-bins">Histograms: Put observations into bins</a></li>
  <li><a href="#histograms-bin-width-matters" id="toc-histograms-bin-width-matters" class="nav-link" data-scroll-target="#histograms-bin-width-matters">Histograms: Bin Width Matters!</a></li>
  <li><a href="#describing-distributions" id="toc-describing-distributions" class="nav-link" data-scroll-target="#describing-distributions">Describing Distributions</a></li>
  <li><a href="#example-what-is-the-shape" id="toc-example-what-is-the-shape" class="nav-link" data-scroll-target="#example-what-is-the-shape">Example: What is the Shape?</a></li>
  <li><a href="#example-what-is-the-shape-1" id="toc-example-what-is-the-shape-1" class="nav-link" data-scroll-target="#example-what-is-the-shape-1">Example: What is the Shape?</a></li>
  <li><a href="#purely-pedagogical-stem-and-leaf-plots." id="toc-purely-pedagogical-stem-and-leaf-plots." class="nav-link" data-scroll-target="#purely-pedagogical-stem-and-leaf-plots.">Purely Pedagogical: Stem-and-Leaf plots.</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  <li><a href="#participation-questions" id="toc-participation-questions" class="nav-link" data-scroll-target="#participation-questions"><span class="header-section-number">1.4</span> Participation Questions</a>
  <ul class="collapse">
  <li><a href="#participation-question-1" id="toc-participation-question-1" class="nav-link" data-scroll-target="#participation-question-1">Participation Question 1</a></li>
  <li><a href="#participation-question-2" id="toc-participation-question-2" class="nav-link" data-scroll-target="#participation-question-2">Participation Question 2</a></li>
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3">Q3</a></li>
  <li><a href="#q4" id="toc-q4" class="nav-link" data-scroll-target="#q4">Q4</a></li>
  <li><a href="#q5" id="toc-q5" class="nav-link" data-scroll-target="#q5">Q5</a></li>
  <li><a href="#q6" id="toc-q6" class="nav-link" data-scroll-target="#q6">Q6</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/DB7-CourseNotes/ST231_S23/edit/main/L01-Intro_PicturingGraphs.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Picturing Distributions with Graphs</span></h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Dr.&nbsp;Devan Becker </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Jam: <em>Penguins</em> by Lyle Lovett
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2023-05-08</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1.1</span> Introduction</h2>
<section id="defining-statistics" class="level3">
<h3 class="anchored" data-anchor-id="defining-statistics">Defining “Statistics”</h3>
<p>My definition: Statistics is the study of <strong>variance</strong> (or uncertainty).</p>
<ul>
<li>The big question: is 1 <strong>statistically different</strong> from 100?
<ul>
<li>1 vs.&nbsp;100 apples? Yes.</li>
<li>1 vs.&nbsp;100 atoms in an apple? No.</li>
</ul></li>
</ul>
<div class="notes">
<p>Many definitions of statistics are based on data. This completely misses theoretical statistics, and makes it seem like it’s all about dealing with data. I think a better definition of statistics is that it’s the study of variance, whether that means studying the theoretical properties of variance or trying to explain variance in a data set.</p>
<p>I like to ask the question is one statistically different from 100. It may seem like they are obviously different things, but consider the context. If you’re comparing numbers of apples, then yes, one apple is very different from having 100 apples. However, if we’re looking at numbers of of atoms per apple than one and 100 are both imperceptible numbers of atoms and thus we might say they’re practically the same. The difference in these two examples is the scale, and variance is a great way to measure the scale of things. In my opinion, the main thing we learned in this course is how to tell whether to numbers are different, given the scale of those two numbers.</p>
<p>In my lecture notes, I use bold font for anything that you will be expected to be able to explain or define. You won’t necessarily be able to find it the first time you see it, but by the midterm/final it is something I expect you to know. A good way to study in this course is to keep a glossary of all of the words I’ve put in bold, with a definition that you update as we learn more about that concept. And, of course, write a description as if you’re teaching someone else!</p>
</div>
</section>
<section id="why-study-variance" class="level3">
<h3 class="anchored" data-anchor-id="why-study-variance">Why study variance?</h3>
<ul>
<li>Give context to different numbers.
<ul>
<li>The size of the difference depends on the context.</li>
</ul></li>
<li>We need to know <em>how</em> and <em>why</em> we were wrong.
<ul>
<li><em>How</em>: What is the magnitude of the difference?</li>
<li><em>Why</em>: Are we missing relationships? Bad sampling? Fundamental randomness?</li>
</ul></li>
</ul>
<p>Variance is information!</p>
<div class="notes">
<p>Variance comes from many sources. We might just be doing something wrong and missing out on important feature of our data, we might be collecting the data in a biased or incorrect way, or there might be some fundamental part of the problem that we will never be able to measure perfectly, and so the variance that we calculated may already be the smallest possible variance for this problem.</p>
<p>I like to see that variances information. Think about an example, we’re trying to figure out the heights of undergraduate students. We can calculate an average height, but it is entirely possible that nobody in our data set is exactly the average height. We would want to quantify how much variation there is around that average height. If our sample includes a basketball team, then, this is variation due to some thing that we could have measured. In other words, the variation in our data can be explained by including another perspective. Once we have that perspective and we were included in our analysis are variance should be smaller, and that we have extracted more information. As we gain more information about our data, the variance in our estimate goes down - this is why I say that variance is information!</p>
</div>
</section>
<section id="descriptive-versus-inferential-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-versus-inferential-statistics">Descriptive Versus Inferential Statistics</h3>
<ul>
<li><strong>Descriptive statistics</strong> are used to explore the data.
<ul>
<li>Graphs/figures</li>
<li>Numbers</li>
</ul></li>
<li><strong>Inferential statistics</strong> relate our data to the <strong>population</strong>.
<ul>
<li>Must have a good <strong>sample</strong> first!</li>
<li>Our sample has a mean. The population has a mean. How different do we expect them to be?
<ul>
<li><strong>how different</strong></li>
</ul></li>
</ul></li>
</ul>
<div class="notes">
<p>In this course, we will learn about two classes of statistics. Descriptive statistics are the ones that we used to describe the sample that we obtained. This can include things like the mean/median/mode, the variance or the interquartile range, as well as bar charts, histograms box, plots, etc.</p>
<p>Inferential statistics are numbers that we calculate that we think have a relationship to the population. For instance, if we calculate the mean of our data, and we trust that our sample is good, then we expect this sample mean to be somewhat close to the population mean. Any time in this course I talk about the difference between two things. I will always mean it with reference to the variance. In this, since we have a sample mean, as well as some measure of its variance, and this variance tells us how similar we expect the sample mean to be to the population mean. If we have a small sample variance, it means that we have a lot of information about the population mean. Variance is information!</p>
<p>In this course, we’re going to start by talking about descriptive statistics and work our way to inferential statistics.</p>
</div>
</section>
</section>
<section id="descriptive-statistics-plots-and-graphs" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="descriptive-statistics-plots-and-graphs"><span class="header-section-number">1.2</span> Descriptive Statistics: Plots and Graphs</h2>
<section id="the-palmer-penguins-data" class="level3">
<h3 class="anchored" data-anchor-id="the-palmer-penguins-data">The Palmer Penguins Data</h3>
<p>The following data are from the <code>palmerpenguins</code> package. All code shown in the Notes files.</p>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">bill_length_mm</th>
<th style="text-align: right;">body_mass_g</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">39.1</td>
<td style="text-align: right;">3750</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">39.5</td>
<td style="text-align: right;">3800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">40.3</td>
<td style="text-align: right;">3250</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">36.7</td>
<td style="text-align: right;">3450</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">39.3</td>
<td style="text-align: right;">3650</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:39%;">
<ul>
<li>Species can be Adelie, Gentoo, or Chinstrap</li>
<li>Sex is male/female</li>
<li>Bill Length is measured in millimetres</li>
<li>Body Mass is measured in grams</li>
<li>Not shown: Island (one of three), bill depth (mm), flipper length (mm), year.</li>
</ul>
</div>
</div>
<div class="notes">
<p>Let me introduce you to a dataset that I’m going to be returning to throughout the semester. This is called the Palmer penguins data, end it contains information on penguins from several islands in Antarctica. In the slides, I use some fancier code to only show some of the data, but I’ll display the full data set with simpler code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">as.data.frame</span>(penguins))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species    island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1  Adelie Torgersen           39.1          18.7               181        3750
2  Adelie Torgersen           39.5          17.4               186        3800
3  Adelie Torgersen           40.3          18.0               195        3250
4  Adelie Torgersen             NA            NA                NA          NA
5  Adelie Torgersen           36.7          19.3               193        3450
6  Adelie Torgersen           39.3          20.6               190        3650
     sex year
1   male 2007
2 female 2007
3 female 2007
4   &lt;NA&gt; 2007
5 female 2007
6   male 2007</code></pre>
</div>
</div>
<p>These data are really nice for this purpose because we can look at what factors contribute to body mass, species or biological sex. It’s not shown in the slides, but we can see here that we also have measurements on flipper length and bill width.</p>
</div>
</section>
<section id="types-of-variables" class="level3">
<h3 class="anchored" data-anchor-id="types-of-variables">Types of Variables</h3>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">body_mass_g</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">3750</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">3800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">3250</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">3450</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">3650</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Species is <strong>categorical</strong>
<ul>
<li>Mutually exclusive categories.</li>
</ul></li>
<li>Sex is <strong>binary</strong>
<ul>
<li>One or the other</li>
<li>Special case of categorical with 2 cats</li>
</ul></li>
<li>Body mass is <strong>quantitative</strong>
<ul>
<li>It’s a number (quantity)</li>
</ul></li>
</ul>
</div>
</div>
<div class="notes">
<p>The type of variable is extremely important for choosing the right summary of the data.</p>
<p>Categorical variables consist of two or more mutually exclusive categories, that is, each observation has a label and nothing has more than one label. Categorical variables may be ordered (such as “low”, “medium”, and “high”) or unordered (such as names or student numbers; putting names in alphabetical order is not usually meaningful for summarising the data or doing the analysis).</p>
<p>Binary variables are a special case of categorical variables, which only have two categories.</p>
<p>The distinction between categorical and quantitative isn’t always this obvious, but can be very helpful for choosing the right kind of plot or numerical summary.</p>
</div>
</section>
<section id="grey-areas" class="level3">
<h3 class="anchored" data-anchor-id="grey-areas">Grey Areas</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Student Numbers
</div>
</div>
<div class="callout-body-container callout-body">
<p>A student number looks like a quantitative variable, but it’s actually just a name (category)!</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Number of Children
</div>
</div>
<div class="callout-body-container callout-body">
<p>If there are only counts of 0, 1, and 2, you might want to consider the counts as categories.</p>
</div>
</div>
<div class="notes">
<p>There are a couple gray areas when talking about variable types. The distinction between categorical and quantitative isn’t always perfectly clear. For example, student numbers are names, but they are completely made up of numbers. However, you wouldn’t treat these numbers as if one student number comes after another in the same way that you wouldn’t put students in an order based on their names. You technically can do this if you do it alphabetically or order the student numbers in order, but this isn’t a meaningful ordering. It’s not like one student number is larger than another student number, and taking the meaning of student numbers wouldn’t make any sense.</p>
<p>Another gray area is a counting variable that has low counts. For example, if you only have zero one or two children as possible values, tt might make more sense to look at all of the people with zero children, look at all the people with one child, and then look at all the people with two children, rather than making a plot that treats the number of children as if it can be any value between zero and infinity.</p>
</div>
</section>
<section id="individuals-subjects" class="level3">
<h3 class="anchored" data-anchor-id="individuals-subjects">Individuals (Subjects)</h3>
<p><strong>Individual:</strong> the unit of study.</p>
<p>In the Palmer Penguins data set, a penguin is an individual.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CO<span class="math inline">\(_2\)</span> Measurements
</div>
</div>
<div class="callout-body-container callout-body">
<p>Monthly measurements of CO<span class="math inline">\(_2\)</span> - the months are the individuals?</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Paired Observations
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Spousal pairs - the pairs are the individuals?</li>
<li>Before/after (e.g., weight loss) - people are individuals.</li>
</ul>
</div>
</div>
<div class="notes">
<p>All of the variables we just talked about our measured on individuals. That is to say an individual is what you are measuring when collecting data. This can take the form of a single penguin, in which case it’s obvious that this body mass belongs to this penguin; we have measured this body mass on this.</p>
<p>There are some gray areas to this as well, though. For example, if we’re measuring carbon dioxide every month, then we’re actually measuring carbon dioxide as the variable and months as the individuals, and we can measure other things on those individuals if needed.</p>
<p>We will also encounter pared observations in this course, which our measurements on two things at once. For example, we might be looking at spousal pairs, perhaps measuring the number of children per pair. The variable we are measuring is the number of children, and so we must have one observation of the number of children per individual, which means that the individuals must be the pairs of people. I slightly more obvious example is something like a weight loss study were observing a change in weight for a certain person, even though we have two observations, the individual is still the person who were measuring.</p>
</div>
</section>
<section id="example-what-are-the-individuals-what-are-variables" class="level3">
<h3 class="anchored" data-anchor-id="example-what-are-the-individuals-what-are-variables">Example: What are the Individuals? What are Variables?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mtcars[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg cyl disp  hp drat
Mazda RX4         21.0   6  160 110 3.90
Mazda RX4 Wag     21.0   6  160 110 3.90
Datsun 710        22.8   4  108  93 3.85
Hornet 4 Drive    21.4   6  258 110 3.08
Hornet Sportabout 18.7   8  360 175 3.15
Valiant           18.1   6  225 105 2.76</code></pre>
</div>
</div>
<div class="notes">
<ul>
<li>Individuals: Each car (not brand)</li>
<li>Variables: <code>wt</code>, <code>mpg</code>, <code>cyl</code>, <code>am</code>, etc.
<ul>
<li><code>wt</code>: Quantitative; the weight of the car.</li>
<li><code>am</code>: Binary (categorical); whether the car is automatic or manual.</li>
<li><code>cyl</code>: It’s the number of cylinders, so it can be considered a number. However, there are only three possible values: 4, 6, or 8. We <em>could</em> consider these numbers, but it is likely more useful to think of 4 cylinder cars in one category, 6 cylinder in another category, and 8 cylinder in the last category. This way, when we do analysis, we are just comparing categories rather than see what happens when we add cylinders (“adding cylinders” makes it sound like we might add 1 cylinder to a 4 cylinder car, or liek we might make predictions about what would happen with a 2 cylinder car).</li>
</ul></li>
</ul>
</div>
</section>
</section>
<section id="graphs" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="graphs"><span class="header-section-number">1.3</span> Graphs</h2>
<section id="words-are-hard" class="level3">
<h3 class="anchored" data-anchor-id="words-are-hard">Words are Hard</h3>
<p>Graph, chart, plot are <em>usually</em> synonyms.</p>
<ul>
<li><em>Graph theory</em> refers to graphs with edges and notes.</li>
<li><em>Plotting</em> refers to making a visual representation of information.
<ul>
<li>Applies to more than just data.</li>
</ul></li>
<li><em>Charts</em> are plots that are meant to compare things.</li>
</ul>
<p>Takeaway message: A bar chart and a bar plot are the same thing.</p>
<div class="notes">
<p>In this class, we’ll use them all interchangably.</p>
</div>
</section>
<section id="pie-charts" class="level3">
<h3 class="anchored" data-anchor-id="pie-charts">Pie Charts</h3>
<ul>
<li>The wedges must sum to 1.</li>
<li>Mainly good for <em>emphasizing</em> one wedge
<ul>
<li><em>Emphasizing</em> can mean <em>misrepresenting</em>!</li>
</ul></li>
</ul>
<p><a href="https://www.darkhorseanalytics.com/blog/salvaging-the-pie">https://www.darkhorseanalytics.com/blog/salvaging-the-pie</a></p>
<div class="notes">
<p>In this course, I will not be providing you the code required to make a pie chart. However, you should understand what a pie chart is, what data it works for, and how they relate to bar charts.</p>
</div>
</section>
<section id="bar-charts-categories" class="level3">
<h3 class="anchored" data-anchor-id="bar-charts-categories">Bar Charts: Categories</h3>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(am)) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Transmission Type"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>ggplot</code> calculates the <span class="math inline">\(y\)</span> values for you!</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>Compare this to the output of <code>table(mtcars$am)</code>.</p>
<div class="notes">
<p>Bar charts are primarily used to compare categories. The most common use of a bar chart is to count the number of observations in each category, and create a bar with a corresponding height. In this example, we see, automatic and manual transmissions, with automatic labelled as zero and manual labelled as one. We can see that approximately 22 cars are automatic and 13 cars are manual. Unlike a pie chart, we can read these numbers off of the plot and it’s easy to compare these two categories.</p>
<p>The code required to create this bar chart as shown on the left. The data set is built into our so we don’t need to load anything to put this data. We do need to load in the <code>ggplot</code> library, though. In my lecture notes, you’ll see lots of code that looks like this, but you will not be tested on your ability to re-create this code. For those interested, here’s a quick breakdown of the functions I used:</p>
<ul>
<li>The ggplot function tells R what data we will be using.</li>
<li>The <code>aes()</code> function sets up the plot “aesthetics”, such as what variable goes on the x-axis, what variable goes on the y-axis, what variable is assigned to a colour, what variable determines the shapes of points etc.</li>
<li><code>geom_bar()</code> actually makes the bar plot using the data set that <code>ggplot()</code> set up and the aesthetics, that <code>aes()</code> set up.</li>
<li>The <code>labs()</code> function simply adds labels to the plot to make it look nicer.</li>
</ul>
<p><strong>Exercises</strong></p>
<p>The following exercises are based on the exercises in Chapter 1 of Baldi &amp; Moore, 4th ed.</p>
<ol type="1">
<li>Children’s food choices. Does the presence of popular cartoon characters on food packages influence children’s food choices? A study asked 40 young children (ages four to six) to taste two small pieces of Graham Crackers coming from a package with and a package without a popular cartoon character, and to indicate whether the two foods tasted the same or one tasted better. Unknown to the children, the crackers were the same both times. Here are the findings:</li>
</ol>
<table class="table">
<thead>
<tr class="header">
<th>Taste Preference</th>
<th>Number of Children</th>
<th>Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tastes better without character</td>
<td>3</td>
<td></td>
</tr>
<tr class="even">
<td>Taste the same</td>
<td>15</td>
<td></td>
</tr>
<tr class="odd">
<td>Tastes better with character</td>
<td>22</td>
<td></td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Identify the individuals and the variable or variables in the study.</li>
<li>Present these data in a well-labeled bar graph.</li>
<li>Would it also be correct to present these data in a single pie chart? Explain your reasoning.</li>
<li>What do the data suggest about the influence of cartoon characters on Graham Cracker preference in young children</li>
</ol>
<ol start="2" type="1">
<li>The study in Exercise 1 also asked the 40 children to taste small pieces of gummy fruit snacks and baby carrots presented in packages with and in packages without a popular cartoon character. For each food type, the children indicated which of the two options they would prefer to eat for a snack. (Note that this is a different question from the one asked in Exercise 1) The number and percent of children choosing the version with a cartoon on the package are displayed in the following table:</li>
</ol>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Food Item</th>
<th>Number of children choosing the cartooon version</th>
<th>Percent choosing the cartoon</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Graham Crackers</td>
<td>35</td>
<td></td>
</tr>
<tr class="even">
<td>Gummy and fruit snacks</td>
<td>34</td>
<td></td>
</tr>
<tr class="odd">
<td>Baby carrots</td>
<td>29</td>
<td></td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Identify the individuals and the variable or variables in the study.</li>
<li>Make a well-labeled bar graph of the data.</li>
<li>Would it be correct to present these data in a single pie chart? Explain your reasoning.</li>
<li>What can you conclude from these findings?</li>
</ol>
</div>
</section>
<section id="quantitative-variables" class="level3">
<h3 class="anchored" data-anchor-id="quantitative-variables">Quantitative Variables</h3>
<ul>
<li>Discrete (whole numbers)
<ul>
<li>Ex. Number of students in a classroom.</li>
</ul></li>
<li>Continuous (could be measured with more precision)
<ul>
<li>Ex. height</li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Grey Area
</div>
</div>
<div class="callout-body-container callout-body">
<p>What type of variable is “dose level”, defined as either no dose, half dose, or full dose? They aren’t whole numbers, but we can’t measure them with greater precision!</p>
</div>
</div>
<div class="notes">
<p>Quantitative variables are split into discrete and continuous variables. Discrete variables are generally represented by whole numbers, for example, the number of students in a given classroom.</p>
<p>In contrast, continuous numbers could be anything! I like to think of them as numbers that could’ve been measured with more precision if we had better tools. For example, peoples Heights could be measured to infinite precision if we had perfect tools, whereas we don’t need better tools to measure the number of children and family more precisely.</p>
<p>Of course, as with all things, there is a gray area here. Many studies will choose to give their subjects either no dose, a half dose or a full dose. These are obviously numbers and it is very likely that the response for a 0.75 dose is somewhere in between the half dose and the full dose. However, we chose these numbers and thus there are only three possible numbers. No amount of measuring is going to give us something other than a half dose (any deviation in administration of the dose can hopefully be ignored for the purpose of the study). In the definitions we’ve used it is neither a whole number, nor cannot be measured with higher precision. For the purposes of visualization, we might actually want to use a bar chart as if this were a categorical variable. If the dose had more categories and we expected the response to have a smooth trend across different dose levels, then we might use visualizations meant for discrete data. If the dose could have been any number between zero and one then we might use visualization meant for continuous data.</p>
</div>
</section>
<section id="quantitative-variables-1" class="level3">
<h3 class="anchored" data-anchor-id="quantitative-variables-1">Quantitative Variables</h3>
<p>Here are the lengths of sharks:</p>
<pre><code> 9.4 12.1 12.2 12.3 12.4 12.6 13.2 13.2 13.2 13.2 13.5
13.6 13.6 13.8 14.3 14.6 14.7 14.9 15.2 15.3 15.7 15.7
15.8 15.8 16.1 16.2 16.2 16.4 16.4 16.6 16.7 16.8 16.8
17.6 17.8 17.8 18.2 18.3 18.6 18.7 18.7 19.1 19.7 22.8</code></pre>
<ul>
<li>We could have measured more precisely!</li>
<li>Can’t just draw a bar chart with all sharks that were 9.4, all that were 12.1, …</li>
</ul>
<div class="notes">
<p>How many we display this collection of shark lengths? It is clear that there are many different values that we could’ve gotten for the length and so we might not want to use something like a bar chart.</p>
</div>
</section>
<section id="quantitative-variables-as-a-bar-chart" class="level3">
<h3 class="anchored" data-anchor-id="quantitative-variables-as-a-bar-chart">Quantitative Variables as a Bar Chart</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="notes">
<p>This plot demonstrates why bar chart isn’t appropriate for these data. We can see that each data point essentially gets its own bar, and so the heights are no longer meaningful. The exception is that these data are rounded, and so some lengths end up in the same bar. Knowing that some of our data are rounded to the same value is not necessarily meaningful for any analyses that we might want to do. Instead, we would like a chart that shows us where most of the data are, and whether or not they are clear patterns in these data.</p>
</div>
</section>
<section id="histograms-put-observations-into-bins" class="level3">
<h3 class="anchored" data-anchor-id="histograms-put-observations-into-bins">Histograms: Put observations into bins</h3>
<div class="columns">
<div class="column" style="width:50%;">
<p>The steps in building a histogram:</p>
<ol type="1">
<li>Choose the bins.
<ul>
<li>e.g.&nbsp;(0,10], (10,20], (20, 30], etc.</li>
</ul></li>
<li>Count the number of obs. in each bin.</li>
<li>Draw a bar chart as if the bins are categories.
<ul>
<li>Bars should touch since there’s nothing in between.</li>
</ul></li>
</ol>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>Bins are (0,1], (1,2], (2,3]…</p>
<p>Notice how the y-axis is still “Counts” (like a bar chart).</p>
</div>
</div>
<div class="notes">
<p>Most of the time we will probably want to use a histogram to display quantitative, continuous data. A histogram is very much like putting continuous numbers into discrete bins, and then showing it as a bar chart. In this example, I chose bins from 1 to 3, then 3 to 5, then 5 to 7, and so on. For the bar on this histogram centred at a shark length of 12 we can see that there were five observations between 11 and 13. Note that the definitions of bins has a round bracket on the left side and the square bracket on the right side, this is to say that the left end point <em>is not</em> included but the right end point <em>is</em> included. This is just to account for cases where X may fall directly on the border between two bins, and we have to choose which bin. The actual bin we choose is arbitrary kind of like driving in the left or the right. You will not be tested on whether you can remember which endpoint is inclusive.</p>
<p>From the plot on the right, we can see that most of the sharks are around 16 feet in length with sun going down to 10 feet and some as long as around 22 feet. The plot has a nice bell shape.</p>
<p>A simple version of the plot can be made as follows, where <code>ggplot</code> chooses the bins automatically. Note that this is rarely desireable, and you should almost always choose the bins yourself.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Below is an app to visualize the difference that the binwidth can make!</p>
</div>
</section>
<section id="histograms-bin-width-matters" class="level3">
<h3 class="anchored" data-anchor-id="histograms-bin-width-matters">Histograms: Bin Width Matters!</h3>
These histograms are showing the same data!
<div class="columns">
<div class="column" style="width:48%;">
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div><div class="column" style="width:48%;">
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<div class="notes">
<p>In the previous graph, it looked like the distribution of sharks followed a nice bell curve. However, if we use bins that are 1.5 units wide we get a plot that looks fairly different. It still looks like most sharks are around 16 feet and some go down to 10 and some go as high is 22 or 23, But we see a large bar that covers 12 to 13.5. This no longer has a nice bell shaped to it, but still looks relatively the same.</p>
<p>With histograms the bins that you choose are extremely important. Most software have default values that are generally reasonable, But it’s always always always worth investigating other bins.</p>
</div>
</section>
<section id="describing-distributions" class="level3">
<h3 class="anchored" data-anchor-id="describing-distributions">Describing Distributions</h3>
<p>When you’re asked to comment on a histogram, always mention the following:</p>
<ul>
<li><strong>Shape</strong>: <strong>Unimodal</strong>/<strong>bimodal</strong> and <strong>skewness</strong>
<ul>
<li>Skewness: put a glob of peanut butter on toast, “skew” it to one side.</li>
</ul></li>
<li><strong>Center</strong>: midpoint (<strong>mean</strong>/<strong>median</strong>)
<ul>
<li><strong>Mode</strong> depends on the bin!</li>
<li>Skewness shows up in the relation between mean and median: “Mean less (than median) means left (skew).”</li>
</ul></li>
<li><strong>Spread</strong>: the <strong>range</strong>/<strong>variance</strong>/<strong>IQR</strong>
<ul>
<li>More on IQR later!</li>
</ul></li>
<li><strong>Outliers</strong>: points that don’t fit the shape
<ul>
<li>More on outliers when we cover IQR!</li>
</ul></li>
</ul>
<div class="notes">
<p>There are many shapes that a histogram can show. A distribution can be skewed (or “heavy-tailed”), which means that it looks like a bell curve but one side has a longer/thicker tail. We also want to know about several measures of the center of the distribution, as well as how spread out it is. Outliers are also something interesting to note; outliers are something that are <em>not</em> part of the shape (so you wouldn’t consider them when evaluating the skewness of a distribution).</p>
<p>Try drawing out each of these shapes/patterns!</p>
</div>
</section>
<section id="example-what-is-the-shape" class="level3">
<h3 class="anchored" data-anchor-id="example-what-is-the-shape">Example: What is the Shape?</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="notes">
<p>This represents a <strong>bimodal</strong> distribution because it has two peaks (the word “mode” can refer to the category with the most observations, but it can also refer to the top of a peak). This would be described as a bimodal distribution with centres around 190 and 215, ranges around 195 to 205 and 205 to 235, with both peaks being symmetric and without any outliers.</p>
</div>
</section>
<section id="example-what-is-the-shape-1" class="level3">
<h3 class="anchored" data-anchor-id="example-what-is-the-shape-1">Example: What is the Shape?</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="notes">
<p>This is the classic sort of gotcha question that I like to use. This is actually a bar chart that I modified so that the bars have no space in-between - the x-labels are categories, not ranges! It may look somewhat symmatric and unimodal without any outliers, but the x-labels are actually out of order. These numbers are actually just numerical encodings of species names - 1 refers to Adelie penguins, 2 refers to Chinstrap, and 3 refers to Gentoo. These numbers were applied alphabetically because there isn’t really a logical way to order these species: they’re unordered categories!</p>
<p>So, basically, it does not make sense to talk about shape in a bar graph where the labels could have been put in any order!</p>
</div>
</section>
<section id="purely-pedagogical-stem-and-leaf-plots." class="level3">
<h3 class="anchored" data-anchor-id="purely-pedagogical-stem-and-leaf-plots.">Purely Pedagogical: Stem-and-Leaf plots.</h3>
<p>Consider the data</p>
<pre><code>12, 43, 12, 32, 53, 66, 78, 25, 36, 12, 26,
34, 98, 39, 44, 23, 15, 67, 1,  4,  54, 21</code></pre>
<div class="columns">
<div class="column" style="width:30%;">

</div><div class="column" style="width:20%;">
<p><strong>Stem-and-Leaf</strong></p>
<pre><code>0  | 14
10 | 2225
20 | 1356
30 | 2469
40 | 34
50 | 34
60 | 67
70 | 8
80 |
90 | 8</code></pre>
</div><div class="column" style="width:50%;">
<p><strong>Sideways Histogram</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<div class="notes">
<p>This visualization technique is shown purely for pedagogical reasons. A stem and leaf plot is like a histogram where the bins are all powers of 10. It isisplayed using the stem, which is the first digit and the leaf which is the second digit. For example, the number 78 has a 7 in the tens place (and were using the tens place as the stem) and an 8 in the ones place (and we using the ones place as the leaf). In the stem and leaf plot, 78 goes on the stem labelled 70 and it gets a leaf of eight. Going the other way, we can see a stem labelled 90 and a leaf labelled eight which corresponds to the number 98. For the stem labelled zero we have the numbers one and four, for the stem label 10 we have the numbers 12, 12, 12, and 15, and so on.</p>
<p>Essentially, this is just a histogram. We’re instead of drawing a bar that corresponds to the number of observations in that bin, we are just listing the observations in that bin. Compare the stem and leaf plot to the sideways histogram on the right: in the first bin from 0 to 10 (not including 10) there are two numbers, one and four, and the length of the bin is two. For the stem label 20, we have the numbers 21, 23, 25 and 26, and this is displayed as a bar with link for in the histogram.</p>
<p>The main reason for showing this visualization technique is that it can be very useful for tests and quizzes, because it allows you to create a histogram without software. It also allows easy computation of the median since all of the leaves are in order. These are not used in practice, because in practice, you will have software to create histograms <em>and</em> find the median!</p>
<p>Note that the shape of the distribution can be seen from the stem and leaf plot. It is a unimodal distribution that is right skewed and likely does not have an outlier (there is one point that appears to be separate from the others, but this is likely due to bin choice).</p>
</div>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<ul>
<li><strong>Individuals</strong> are what we make measurements on
<ul>
<li>Can be pairs, dates, or people</li>
</ul></li>
<li><strong>Variables</strong> are what we measure
<ul>
<li>Can be derived from other measurements</li>
</ul></li>
<li>You will not be asked to do anything with pie charts in this course.</li>
<li><strong>Bar charts</strong> show counts of categories.
<ul>
<li>Can optionally sum to 1 (like a pie chart).</li>
</ul></li>
<li><strong>Histograms</strong> are like bar charts for binned data.
<ul>
<li><strong>Bins matter</strong>.</li>
<li>Must interpret <strong>shape</strong>.</li>
</ul></li>
</ul>
</section>
</section>
<section id="participation-questions" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="participation-questions"><span class="header-section-number">1.4</span> Participation Questions</h2>
<section id="participation-question-1" class="level3">
<h3 class="anchored" data-anchor-id="participation-question-1">Participation Question 1</h3>
<p>Which of the following visualizations would be <em>least</em> appropriate for <strong>discrete</strong> data?</p>
<ol type="1">
<li>Bar Chart</li>
<li>Histogram</li>
<li>Pie Chart</li>
<li>Stem-and-Leaf plot</li>
</ol>
</section>
<section id="participation-question-2" class="level3">
<h3 class="anchored" data-anchor-id="participation-question-2">Participation Question 2</h3>
<div class="columns">
<div class="column" style="width:50%;">
<p>What shape is the distribution on the right?</p>
<ol type="1">
<li>Symmetric</li>
<li>Left Skewed</li>
<li>Right Skewed</li>
</ol>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</section>
<section id="q3" class="level3">
<h3 class="anchored" data-anchor-id="q3">Q3</h3>
<p>Age was collected as the number of days since birth. What kind of variable is this?</p>
<ol type="1">
<li>Ordered categorical</li>
<li>Unorded categorical</li>
<li>Discrete</li>
<li>Continuous</li>
</ol>
</section>
<section id="q4" class="level3">
<h3 class="anchored" data-anchor-id="q4">Q4</h3>
<p>Age was collected as 0-17, 18-25, 25-34, or 35+. What kind of variable is this?</p>
<ol type="1">
<li>Ordered categorical</li>
<li>Unorded categorical</li>
<li>Discrete</li>
<li>Continuous</li>
</ol>
</section>
<section id="q5" class="level3">
<h3 class="anchored" data-anchor-id="q5">Q5</h3>
<p>Age was collected as age in years, then rounded to the nearest 10. What kind of variable is the rounded value of age?</p>
<ol type="1">
<li>Ordered categorical</li>
<li>Unorded categorical</li>
<li>Discrete</li>
<li>Continuous</li>
</ol>
</section>
<section id="q6" class="level3">
<h3 class="anchored" data-anchor-id="q6">Q6</h3>
<div class="columns">
<div class="column" style="width:50%;">
<p>Approximately what proportion of the data is larger than 0? Note that there are 40 data points.</p>
<ol type="1">
<li>50%</li>
<li>25%</li>
<li>75%</li>
<li>100%</li>
</ol>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="480"></p>
</div>
</div>
</div>
</div>
<div class="notes">
<p><strong>Exercises</strong></p>
<ol type="1">
<li><strong>Prescriptions of opioid pain relievers.</strong> Opioid pain relievers are prescribed at a higher rate in the United States than in any other nation, even though abuse of these medications can result in addiction and fatal overdoses. The CDC examined opioid pain reliever prescriptions in each state to find out how variable prescription rates are across the nation. Here are the 2012 state prescription rates, in number of prescriptions per 100 people, listed in increasing order:</li>
</ol>
<p><code>opiods &lt;- c(52.0, 57.0, 59.5, 61.6, 62.9, 65.1, 66.5, 67.4, 67.9, 69.6, 70.8, 71.2, 71.7, 72.4, 72.7, 72.8, 73.8, 74.3, 74.3, 74.7, 76.1, 77.3, 77.5, 79.4, 82.0, 82.4, 85.1, 85.6, 85.8, 88.2, 89.2, 89.6, 90.7, 90.8, 93.8, 94.1, 94.8, 96.6, 100.1, 101.8, 107.0, 109.1, 115.8, 118.0, 120.3, 127.8, 128.4, 137.6, 142.8, 142.9)</code></p>
<ol type="a">
<li>Make a histogram of the state opioid pain reliever prescription rates using classes of width 10 starting at 50.0 prescriptions per 100 people. e.g.&nbsp;(50, 60]. Do this by hand first, then using R.</li>
<li>Would you say that the distribution is single-peaked or multiple-peaked? Is it roughly symmetric or skewed?</li>
</ol>
<p>The Statistical Abstract of the United States, prepared by the Census Bureau, provides the number of single-organ transplants for the year 2010, by organ. The following two exercises are based on this table:</p>
<table class="table">
<thead>
<tr class="header">
<th>Disease</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Heart</td>
<td>2,333</td>
</tr>
<tr class="even">
<td>Lung</td>
<td>1,770</td>
</tr>
<tr class="odd">
<td>Liver</td>
<td>6,291</td>
</tr>
<tr class="even">
<td>Kidney</td>
<td>16,898</td>
</tr>
<tr class="odd">
<td>Pancreas</td>
<td>350</td>
</tr>
<tr class="even">
<td>Intestine</td>
<td>151</td>
</tr>
</tbody>
</table>
<ol start="2" type="1">
<li>(1.14 in BM) The data on single-organ transplants can be displayed in</li>
</ol>
<ol type="a">
<li>a pie chart but not a bar graph.</li>
<li>a bar graph but not a pie chart.</li>
<li>either a pie chart or a bar graph.</li>
</ol>
<ol start="3" type="1">
<li>(1.15 in BM) Kidney transplants represented what percent of single- organ transplants in 2010?</li>
</ol>
<ol type="a">
<li>Nearly 61%.</li>
<li>One-sixth (nearly 17%).</li>
<li>This percent cannot be calculated from the information provided in the table.</li>
</ol>
<p>See also: <a href="https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_OpenIntro_Statistics_(Diez_et_al)./01%3A_Introduction_to_Data/1.E%3A_Introduction_to_Data_(Exercises)">OpenIntro Textbook</a> problems relating to visualizations that we have learned, especially 1.30, 1.36, 1.37, 1.39, 1.40, 1.47.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./L02-Describing_Distributions_Numbers.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions with Numbers</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>