<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Devan Becker">
<meta name="dcterms.date" content="2023-12-20">

<title>Statistics for Life Sciences - 1&nbsp; Picturing Distributions with Graphs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./L02-Describing_Distributions_Numbers.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Picturing Distributions with Graphs</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for Life Sciences</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/DB7-CourseNotes/ST231_S23" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="./Statistics-for-Life-Sciences.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle sidebar-tool" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Pre-Midterm</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L01-Intro_PicturingGraphs.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Picturing Distributions with Graphs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L02-Describing_Distributions_Numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions with Numbers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L03-Scatterplots_Correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Scatterplots and Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L04-Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L05-Probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability Background</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L07-Normal_Distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Normal Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L09-Binomial_Probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Binomial Probabilities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L10-Sampling_Distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Post-Midterm</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L12-Intro_to_Inference-CI-pvals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Welcome to Inference!</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L13-p_vals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Tests of Significance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L14-Inference_Cautions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Special Topics in Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L15-CI_for_Means.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence Intervals in Practice</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L16-Hypothesis_Tests_for_Means.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">t-Tests for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L17-Two_Sample_hypothesis_Tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Two-Sample t-Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L18-Hypothesis_Tests_for_Proportions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Large sample test for a proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L19-CI_for_Proportions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L20-Two_Proportions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for the Difference in Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L21-ChiSquare_Multiple_Proportions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Chi-Square Test for Multiple Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L22-Inference_for_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L23-ANOVA-oi.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Comparing means with ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L24-Review.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Post-Midterm Review</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">1.1</span>  Introduction</a>
  <ul class="collapse">
  <li><a href="#defining-statistics" id="toc-defining-statistics" class="nav-link" data-scroll-target="#defining-statistics">Defining “Statistics”</a></li>
  <li><a href="#why-study-variance" id="toc-why-study-variance" class="nav-link" data-scroll-target="#why-study-variance">Why study variance?</a></li>
  <li><a href="#descriptive-versus-inferential-statistics" id="toc-descriptive-versus-inferential-statistics" class="nav-link" data-scroll-target="#descriptive-versus-inferential-statistics">Descriptive Versus Inferential Statistics</a></li>
  </ul></li>
  <li><a href="#descriptive-statistics-plots-and-graphs" id="toc-descriptive-statistics-plots-and-graphs" class="nav-link" data-scroll-target="#descriptive-statistics-plots-and-graphs"><span class="toc-section-number">1.2</span>  Descriptive Statistics: Plots and Graphs</a>
  <ul class="collapse">
  <li><a href="#the-palmer-penguins-data" id="toc-the-palmer-penguins-data" class="nav-link" data-scroll-target="#the-palmer-penguins-data">The Palmer Penguins Data</a></li>
  <li><a href="#types-of-variables" id="toc-types-of-variables" class="nav-link" data-scroll-target="#types-of-variables">Types of Variables</a></li>
  <li><a href="#grey-areas" id="toc-grey-areas" class="nav-link" data-scroll-target="#grey-areas">Grey Areas</a></li>
  <li><a href="#individuals-subjects" id="toc-individuals-subjects" class="nav-link" data-scroll-target="#individuals-subjects">Individuals (Subjects)</a></li>
  <li><a href="#challenge-what-are-the-individuals" id="toc-challenge-what-are-the-individuals" class="nav-link" data-scroll-target="#challenge-what-are-the-individuals">Challenge: What are the individuals?</a></li>
  <li><a href="#example-what-are-the-individuals-what-are-variables" id="toc-example-what-are-the-individuals-what-are-variables" class="nav-link" data-scroll-target="#example-what-are-the-individuals-what-are-variables">Example: What are the Individuals? What are Variables?</a></li>
  </ul></li>
  <li><a href="#graphschartsplots" id="toc-graphschartsplots" class="nav-link" data-scroll-target="#graphschartsplots"><span class="toc-section-number">1.3</span>  Graphs/Charts/Plots</a>
  <ul class="collapse">
  <li><a href="#pie-charts" id="toc-pie-charts" class="nav-link" data-scroll-target="#pie-charts">Pie Charts</a></li>
  <li><a href="#bar-charts-categories" id="toc-bar-charts-categories" class="nav-link" data-scroll-target="#bar-charts-categories">Bar Charts: Categories</a></li>
  <li><a href="#titanic-example" id="toc-titanic-example" class="nav-link" data-scroll-target="#titanic-example">Titanic Example</a></li>
  <li><a href="#ordered-and-unordered" id="toc-ordered-and-unordered" class="nav-link" data-scroll-target="#ordered-and-unordered">Ordered and Unordered</a></li>
  <li><a href="#quantitative-variables" id="toc-quantitative-variables" class="nav-link" data-scroll-target="#quantitative-variables">Quantitative Variables</a></li>
  <li><a href="#plotting-quantitative-variables" id="toc-plotting-quantitative-variables" class="nav-link" data-scroll-target="#plotting-quantitative-variables">Plotting Quantitative Variables</a></li>
  <li><a href="#quantitative-variables-as-a-bar-chart" id="toc-quantitative-variables-as-a-bar-chart" class="nav-link" data-scroll-target="#quantitative-variables-as-a-bar-chart">Quantitative Variables as a Bar Chart</a></li>
  <li><a href="#histograms-put-observations-into-bins" id="toc-histograms-put-observations-into-bins" class="nav-link" data-scroll-target="#histograms-put-observations-into-bins">Histograms: Put observations into bins</a></li>
  <li><a href="#histograms-bin-width-matters" id="toc-histograms-bin-width-matters" class="nav-link" data-scroll-target="#histograms-bin-width-matters">Histograms: Bin Width Matters!</a></li>
  <li><a href="#describing-distributions" id="toc-describing-distributions" class="nav-link" data-scroll-target="#describing-distributions">Describing Distributions</a></li>
  <li><a href="#example-what-is-the-shape" id="toc-example-what-is-the-shape" class="nav-link" data-scroll-target="#example-what-is-the-shape">Example: What is the Shape?</a></li>
  <li><a href="#example-what-is-the-shape-1" id="toc-example-what-is-the-shape-1" class="nav-link" data-scroll-target="#example-what-is-the-shape-1">Example: What is the Shape?</a></li>
  <li><a href="#purely-pedagogical-stem-and-leaf-plots." id="toc-purely-pedagogical-stem-and-leaf-plots." class="nav-link" data-scroll-target="#purely-pedagogical-stem-and-leaf-plots.">Purely Pedagogical: Stem-and-Leaf plots.</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="toc-section-number">1.4</span>  Exercises</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/DB7-CourseNotes/ST231_S23/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Picturing Distributions with Graphs</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Devan Becker </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2023-12-20</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="introduction" class="level2 page-columns page-full" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1.1</span> Introduction</h2>
<section id="defining-statistics" class="level3">
<h3 class="anchored" data-anchor-id="defining-statistics">Defining “Statistics”</h3>
<p>My definition: Statistics is the study of <strong>variance</strong> (or uncertainty).</p>
<ul>
<li>The big question: is 1 <strong>statistically different</strong> from 100?
<ul>
<li>1 vs.&nbsp;100 apples? Yes.</li>
<li>1 vs.&nbsp;100 atoms in an apple? No.</li>
</ul></li>
</ul>
<div class="notes">
<p>Many people think of “statistics” as something along the lines of “methods for dealing with data”. This completely misses out on theoretical statistics, and makes it seem like statistics is a collection of recipes stating “if you have this data, use this method”. I think a better definition of statistics is that it’s the study of variance, whether that means studying the theoretical properties of variance or trying to “explain” variance<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> in a particular data set.</p>
<p>I like to ask the question: “is 1 statistically different from 100”. It may seem like they are obviously different numbers, but we can’t know that without the context. If you’re comparing numbers of apples, then yes, one apple is very different from 100 apples. However, if we’re looking at numbers of atoms per apple, then one and 100 are both imperceptible numbers of atoms and thus we might say the the two apples are basically the same size. The difference in these two examples is the scale, and the variance is a fantastic way to measure the scales of things. In my opinion, the main thing we will learn in this course is how to tell whether two numbers are different <em>given the scale of those two numbers.</em> Another popular definition for statistics is “putting numbers in context”, and by “in context” they mean “relative to their variance”.</p>
<p>In my lecture notes, I use <strong>bold font</strong> for anything that you will be expected to be able to explain or define. You won’t necessarily see a full definition the first time you see a word in bold, but by the midterm/final it is something I expect you to know. A good way to study in this course is to keep a glossary of all of the words I’ve put in bold, with a definition file/note that you update as we learn more about that concept. And, of course, write a description as if you’re teaching someone else!</p>
</div>
</section>
<section id="why-study-variance" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="why-study-variance">Why study variance?</h3>
<ul>
<li>Give context to different numbers.
<ul>
<li>The size of the difference depends on the context.</li>
</ul></li>
<li>We need to know <em>how</em> and <em>why</em> we were wrong.
<ul>
<li><em>How</em>: What is the magnitude/direction of the difference?</li>
<li><em>Why</em>: Are we missing relationships? Bad sampling? Fundamental randomness?</li>
</ul></li>
</ul>
<p>Variance is information!</p>
<div class="notes page-columns page-full">
<p>Variance comes from many sources. We might just be doing something wrong and missing out on important feature of our data, we might be collecting the data in a biased or incorrect way, or there might be some fundamental part of the problem that we will never be able to measure perfectly, and so the variance that we calculated may actually be the smallest possible variance for this problem.</p>
<div class="page-columns page-full"><p>Suppose we’re trying to figure out the heights of undergraduate students. We can calculate the average height, but I don’t expect anyone in the data to actually have this exact height. Exactly how far away from this average do we expect the other heights to be? The measurement of the expected distance to the mean is called the <strong>variance</strong>.</p><div class="no-row-height column-margin column-container"><span class="aside">The <strong>variance</strong> is a measure of the “usual” distance to the mean - we’ll have a formula for this later.</span></div></div>
<div class="page-columns page-full"><p>If our sample consisted of people walking out of the gym, and out of 50 people sampled we had 20 people who were on the basketball team, we might know a little bit more about our variance. Specifically, we’ll get some students who may or may not be representative of the population as well as some students who are unusually tall. These two groups are fundamentally different, so including both in the same sample will increase our variance. Put another way, the different groups in our data <strong>explain some of the variance</strong> in our data.</p><div class="no-row-height column-margin column-container"><span class="aside">Different subgroups within a sample can help <strong>explain</strong> why the variance is as large as it is.</span></div></div>
<p>This is why I say that the variance is information! More specifically, the difference between a single value and the mean of the data is due to some unexplained phenomena, and learning more about the problem will reduce the variance.</p>
</div>
</section>
<section id="descriptive-versus-inferential-statistics" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="descriptive-versus-inferential-statistics">Descriptive Versus Inferential Statistics</h3>
<ul>
<li><strong>Descriptive statistics</strong> are used to explore the data.
<ul>
<li>Graphs/figures</li>
<li>Numbers</li>
</ul></li>
<li><strong>Inferential statistics</strong> relate our data to the <strong>population</strong>.
<ul>
<li>Must have a good <strong>sample</strong> first!</li>
<li>Our sample has a mean. The population has a mean. How different do we expect them to be?
<ul>
<li><strong>how different</strong></li>
</ul></li>
</ul></li>
</ul>
<div class="notes page-columns page-full">
<div class="page-columns page-full"><p>In this course, we will learn about two classes of statistics. <strong>Descriptive statistics</strong> are the ones that we used to describe the sample that we obtained. This can include things like the mean/median/mode, the variance or the interquartile range, as well as bar charts, histograms box, plots, etc. </p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Descriptive Statistics</strong> describe the data that were acquired.</span></div></div>
<div class="page-columns page-full"><p><strong>Inferential statistics</strong> are numbers that we calculate because we think they have a relationship to the population. For instance, if we calculate the mean of our data and we trust that our sample is good, then we expect this sample mean to be somewhat close to the population mean. Any time in this course I talk about the difference between two things, I will always mean “with reference to a measure of variance”. In this example, we have a sample mean as well as some measure of its variance, and this variance tells us how similar we expect the sample mean to be to the population mean. If we have a small sample variance, it means that we have a lot of information about the population mean. Variance contains information that we haven’t learned yet!<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Inferential Statistics</strong> attempt to describe the population based on the data acquired. This requires a <em>good</em> sample, and it’s why Statistics is such a useful field of study.</span></div></div>
<p>In this course, we’re going to start by talking about descriptive statistics and work our way to inferential statistics (with a detour through probability to show why inferential statistics work so well).</p>
</div>
</section>
</section>
<section id="descriptive-statistics-plots-and-graphs" class="level2 page-columns page-full" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="descriptive-statistics-plots-and-graphs"><span class="header-section-number">1.2</span> Descriptive Statistics: Plots and Graphs</h2>
<section id="the-palmer-penguins-data" class="level3">
<h3 class="anchored" data-anchor-id="the-palmer-penguins-data">The Palmer Penguins Data</h3>
<p>Let me introduce you to a dataset that I’m going to be returning to throughout the semester. This is called the Palmer penguins data, end it contains information on penguins from several islands in Antarctica. In the slides, I use some fancier code to only show some of the data, but I’ll display the full data set with simpler code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">as.data.frame</span>(penguins))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species    island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1  Adelie Torgersen           39.1          18.7               181        3750
2  Adelie Torgersen           39.5          17.4               186        3800
3  Adelie Torgersen           40.3          18.0               195        3250
4  Adelie Torgersen             NA            NA                NA          NA
5  Adelie Torgersen           36.7          19.3               193        3450
6  Adelie Torgersen           39.3          20.6               190        3650
     sex year
1   male 2007
2 female 2007
3 female 2007
4   &lt;NA&gt; 2007
5 female 2007
6   male 2007</code></pre>
</div>
</div>
<ul>
<li>Species can be Adelie, Gentoo, or Chinstrap</li>
<li>Sex can be male or female<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></li>
<li>Bill Length is measured in millimetres</li>
<li>Body Mass is measured in grams</li>
<li>Island (one of three)</li>
<li>Bill depth (mm)</li>
<li>Flipper length (mm)</li>
<li>Year that the penguin was observed.</li>
</ul>
<p>These data are really nice for teaching statistics because we can look at what factors contribute to body mass (since it’s easier to measure the length of a beak than it is to weigh a live penguin), or we can try to determine biosex using these measurements (since penguins normally have no external genitalia, but have other morphological differences). We can also fit a model to determine the species of each penguin so that we can get a full picture of what makes each species unique! All of these are examples of statistical analyses that we will cover in this course.</p>
</section>
<section id="types-of-variables" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="types-of-variables">Types of Variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>penguins[, <span class="fu">c</span>(<span class="st">"species"</span>, <span class="st">"sex"</span>, <span class="st">"body_mass_g"</span>)] <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">body_mass_g</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">3750</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">3800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">3250</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">3450</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">3650</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>Species is <strong>categorical</strong>
<ul>
<li>Mutually exclusive categories.</li>
</ul></li>
<li>Sex is <strong>binary</strong><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>
<ul>
<li>One or the other</li>
<li>Special case of categorical with 2 possibilities</li>
</ul></li>
<li>Body mass is <strong>quantitative</strong>
<ul>
<li>It’s a number (quantity)</li>
</ul></li>
</ul>
<div class="notes page-columns page-full">
<p>The type of variable is extremely important for choosing the right summary of the data.</p>
<div class="page-columns page-full"><p><strong>Categorical variables</strong> consist of two or more mutually exclusive categories, that is, each observation has a label and nothing has more than one label. Categorical variables may be <strong>ordered</strong> (such as “low”, “medium”, and “high”) or <strong>unordered</strong> (such as names or student numbers; putting names in alphabetical order is not usually meaningful for summarising the data or doing the analysis).</p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Categorical variables</strong> are categories. Be careful - some categories are <em>encoded</em> as numbers, such as “group 1” and “group 2”, etc.</span></div></div>
<div class="page-columns page-full"><p>This distinction of “<strong>ordered</strong>” versus “<strong>unordered</strong>” matters to determine what visualization or model you might want to use to compare data within categories. For instance, we might want to see the change in response to a “low” treatment compared to a “medium” or “high” treatment, where we fully expect the response to the treatment to be lower for “low” treatment and higher for “high”. In contrast, suppose we knew the patients’ occupations. We have no expectation that the treatment reponse in the “electrician” group is lower or higher than any other group, because there’s no logical ordering to occupation.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Ordered</strong> and <strong>unordered</strong> categorical variables.</span></div></div>
<div class="page-columns page-full"><p><strong>Binary variables</strong> are a special case of <strong>categorical variables</strong>, which only have two categories. In this case, the ordering is rarely important, and thus we don’t really make the distinction between ordered binary and unordered binary. It’s a single difference either way, so we can just look at the differences within the categories.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Binary</strong> variables.</span></div></div>
<div class="page-columns page-full"><p><strong>Quantitative variables</strong> are those that are measured with numbers. Unlike “low” to “medium” versus “medium” to “high”, we know how big a step it is from 0 to 1 and then 1 to 2. Unlike categorical variables, quantitative variables have a concept of “in-between”; we have nothing between “medium” and “high”, but there are infinite numbers between 1 and 2.</p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Quantitative variables</strong> are numbers.</span></div></div>
<div class="page-columns page-full"><p>There are, however, cases where there <em>aren’t</em> possible measurements between 1 and 2. These are called “<strong>discrete</strong>”<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> For instance, the number of children that some has is either 0, 1, 2, etc. <strong>Discrete</strong> variables are somewhere in between categorical and <strong>continuous variables</strong> (variables that can take be number). Consider the following two examples of discrete variables: the number of children that someone has, and the number of cents in their bank account. In a study, we might want to look at everyone who has no children, everyone who has 1 child, everyone who has 2, etc. However, we would <em>not</em> want to compare everyon who has 0 cents in their bank account, everyone who has 1 cent in their account, 2 cents, 3, cents, etc. In terms of modelling and visualization, we will sometimes treat discrete variables as categorical and sometimes as continuous.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> </p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Discrete</strong> variables only allow for some numbers, such as the numbers of children per family.</span><span class="aside"><strong>Continuous</strong> variables can take any value in a range. For any two possible numbers, there’s another possible number in between them. Alternatively, they can be defined as “any measurement you make could have been more precise.”</span></div></div>
<p>The distinction between categorical and quantitative isn’t always this obvious, but can be very helpful for choosing the right kind of plot or numerical summary.</p>
</div>
</section>
<section id="grey-areas" class="level3">
<h3 class="anchored" data-anchor-id="grey-areas">Grey Areas</h3>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Student Numbers
</div>
</div>
<div class="callout-body-container callout-body">
<p>A student number looks like a quantitative variable, but it’s actually just a name (category)!</p>
</div>
</div>
<div class="notes">
<p>There are a couple gray areas when talking about variable types. The distinction between categorical and quantitative isn’t always perfectly clear. For example, student numbers are names, but they are completely made up of numbers. However, you wouldn’t treat these numbers as if one student number comes after another in the same way that you wouldn’t put students in an order based on their names. You technically can do this if you do it alphabetically or order the student numbers in order, but this isn’t a meaningful ordering. It’s not like one student number is larger than another student number, and taking the meaning of student numbers wouldn’t make any sense.</p>
</div>
</section>
<section id="individuals-subjects" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="individuals-subjects">Individuals (Subjects)</h3>
<div class="page-columns page-full"><p>An individual is the thing we are making measurements on. For example, in the Palmer Penguins data set, a penguin is an individual and we measure their flipper length, bill length, the island they were observed on, etc. In other data sets, we may measure the GDP of countries (countries are the individuals) or the cuteness of dogs.</p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Individual:</strong> the unit of study. We make measurements on individuals.</span></div></div>
</section>
<section id="challenge-what-are-the-individuals" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="challenge-what-are-the-individuals">Challenge: What are the individuals?</h3>
<p>The following data are from the “Titanic” dataset.</p>
<p>Each number defines the count of children who survived the Titanic’s sinking.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Male</th>
<th>Female</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1st class</td>
<td>5</td>
<td>1</td>
</tr>
<tr class="even">
<td>2nd class</td>
<td>11</td>
<td>13</td>
</tr>
<tr class="odd">
<td>3rd class</td>
<td>13</td>
<td>14</td>
</tr>
<tr class="even">
<td>Crew</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
<div class="notes">
<p>There are a couple of ways to interpret this.</p>
<ul>
<li>People: We measured whether an individual survived (one measurement per person).</li>
<li>Class: We have two measurements per class - one for male children, one for female children.</li>
<li>Sex: We have four observations (class 1, 2, 3, or crew).</li>
<li>Finally, we could say we have one observation per class/sex combination.</li>
</ul>
<p>There isn’t one “correct” definition of individual here. However, the way we define individual affects how we might visualize these data!</p>
</div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
CO<span class="math inline">\(_2\)</span> Measurements
</div>
</div>
<div class="callout-body-container callout-body">
<p>If we measure the C0<span class="math inline">\(_2\)</span> at a given location each month, then do the months count as the individuals? This describes <em>time series</em> data, which we won’t cover in this course. However, visualizations of data that are measured over time can reveal a lot of information!<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
</div>
</div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Paired Observations
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Spousal pairs - the pairs are the individuals?</li>
<li>Before/after (e.g., weight loss) - people are individuals.
<ul>
<li>This is the same idea as spousal pairs!</li>
</ul></li>
</ul>
</div>
</div>
<div class="notes page-columns page-full">
<p>All of the variables we just talked about are measured on individuals. That is to say, an individual is what you are measuring when collecting data. This can take the form of a single penguin, in which case it’s obvious that this body mass belongs to this penguin; we have measured this body mass on this.</p>
<p>There are some gray areas to this as well, though. For example, if we’re measuring carbon dioxide every month, then we’re actually measuring carbon dioxide as the variable and months as the individuals, and we can measure other things on those individuals if needed.</p>
<div class="page-columns page-full"><p>We will also encounter <strong>paired observations</strong> in this course, which are measurements on two things at once. For example, we might be looking at spousal pairs, perhaps measuring the difference in height per pair. The variable we are measuring is the <em>difference</em>, and so we only have one observation per individual, which means that the individuals must be the pairs of people. A slightly more obvious example is something like a weight loss study were observing a change in weight for a certain person, even though we have two observations the individual is still the person who we’re measuring.</p><div class="no-row-height column-margin column-container"><span class="aside"><strong>Paired Observations</strong>: a special type of data where the difference (subtraction) of two values is what we are studying.</span></div></div>
</div>
</section>
<section id="example-what-are-the-individuals-what-are-variables" class="level3">
<h3 class="anchored" data-anchor-id="example-what-are-the-individuals-what-are-variables">Example: What are the Individuals? What are Variables?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mtcars[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="fu">c</span>(<span class="st">"wt"</span>, <span class="st">"mpg"</span>, <span class="st">"cyl"</span>, <span class="st">"am"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     wt  mpg cyl am
Mazda RX4         2.620 21.0   6  1
Mazda RX4 Wag     2.875 21.0   6  1
Datsun 710        2.320 22.8   4  1
Hornet 4 Drive    3.215 21.4   6  0
Hornet Sportabout 3.440 18.7   8  0
Valiant           3.460 18.1   6  0</code></pre>
</div>
</div>
<div class="notes">
<ul>
<li>Individuals: Each car (not brand)</li>
<li>Variables: <code>wt</code>, <code>mpg</code>, <code>cyl</code>, <code>am</code>, etc.
<ul>
<li><code>wt</code>: Quantitative; the weight of the car.</li>
<li><code>am</code>: Binary (categorical); whether the car is automatic or manual.</li>
<li><code>cyl</code>: It’s the number of cylinders, so it can be considered a number. However, there are only three possible values: 4, 6, or 8. We <em>could</em> consider these numbers, but it is likely more useful to think of 4 cylinder cars in one category, 6 cylinder in another category, and 8 cylinder in the last category. This way, when we do analysis, we are just comparing categories rather than see what happens when we add cylinders (“adding cylinders” makes it sound like we might add 1 cylinder to a 4 cylinder car, or like we might make predictions about what would happen with a 2 cylinder car).</li>
</ul></li>
</ul>
</div>
</section>
</section>
<section id="graphschartsplots" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="graphschartsplots"><span class="header-section-number">1.3</span> Graphs/Charts/Plots</h2>
<section id="pie-charts" class="level3">
<h3 class="anchored" data-anchor-id="pie-charts">Pie Charts</h3>
<ul>
<li>The wedges must sum to 1.
<ul>
<li>If “Adelie” makes up 44% of the data, it should be 44% of the pie chart.</li>
<li>All penguins are either Adelie, Gentoo, or Chinstrap; no penguins have more than one species.</li>
</ul></li>
<li>Mainly good for <em>emphasizing</em> one wedge
<ul>
<li><em>Emphasizing</em> can easily mean <em>misrepresenting</em>, whether accidentally or on purpose!</li>
</ul></li>
</ul>
<p><a href="https://www.darkhorseanalytics.com/blog/salvaging-the-pie">https://www.darkhorseanalytics.com/blog/salvaging-the-pie</a></p>
<div class="notes">
<p>In this course, I will not be providing you the code required to make a pie chart. However, you should understand what a pie chart is, what data it works for (categories), and how they relate to bar charts.</p>
</div>
</section>
<section id="bar-charts-categories" class="level3">
<h3 class="anchored" data-anchor-id="bar-charts-categories">Bar Charts: Categories</h3>
<p>Bar charts are similar to pie charts, but better in practically every way.</p>
<p>Each bar represents a category, and the height represents the number of observations in that category.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(am)) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Transmission Type"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The code required to create the bar chart can be shown by clicking the “&gt;Code” icon. An explanation of the code is below (but this will <em>not</em> be tested).</p>
<details>
<summary>
<strong>Code Explanation</strong>
</summary>
<p>The data set is built into our so we don’t need to load anything to put this data. We do need to load in the <code>ggplot</code> library, though. In my lecture notes, you’ll see lots of code that looks like this, but you will not be tested on your ability to re-create this code. For those interested, here’s a quick breakdown of the functions I used:</p>
<ul>
<li>The <code>ggplot()</code> function tells R what data we will be using.</li>
<li>The <code>aes()</code> function sets up the plot “aesthetics”, such as what variable goes on the x-axis, what variable goes on the y-axis, what variable is assigned to a colour, what variable determines the shapes of points, etc.</li>
<li><code>geom_bar()</code> actually draws the bar plot using the data set that <code>ggplot()</code> set up and the aesthetics, that <code>aes()</code> set up.
<ul>
<li>Try running the code without this line and see what happens!<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></li>
</ul></li>
<li>The <code>labs()</code> function simply adds <code>lab</code>el<code>s</code> to the plot to make it look nicer.</li>
</ul>
</details>
<p>Compare this to the following table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mtcars<span class="sc">$</span>am)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 0  1 
19 13 </code></pre>
</div>
</div>
<p>Bar charts are primarily used to compare categories. The most common use of a bar chart is to count the number of observations in each category, and create a bar with a corresponding height. In this example, we see, automatic and manual transmissions, with automatic labelled as zero and manual labelled as one. We can see that approximately 19 cars are automatic and 13 cars are manual. Unlike a pie chart, we can read these numbers off of the plot and it’s easy to compare these two categories.</p>
</section>
<section id="titanic-example" class="level3">
<h3 class="anchored" data-anchor-id="titanic-example">Titanic Example</h3>
<p>The following example demonstrates why it’s important to be clear about what an “individual” is. Depending on how we define an individual, we might choose to make a different plot!</p>
<p>If we’re measuring things about different Sexes (“sexes” are “individuals”), we’re doing a different study than if we consider ourselves to be making measurements about different Classes.</p>
<div class="columns">
<div class="column" style="width:45%;">
<p>Based on this plot, we might be asking how “Sex” varies by “Class”.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div><div class="column" style="width:9%;">

</div><div class="column" style="width:45%;">
<p>Based on this plot, we might be asking how “Class” varies by “Sex”.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p><strong>Exercises</strong></p>
<p>The following exercises are based on the exercises in the (optional) OpenIntro biostats textbook. They are based on the <strong>F</strong>unctional polymorphisms <strong>A</strong>ssociated with human <strong>Mu</strong>scle <strong>S</strong>ize and <strong>S</strong>trength, or <code>famuss</code>, data set.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
<p>The data are available in the <code>oibiostat</code> pacjage in R, which is a package based on the OpenIntro Biostat textbook. Don’t worry if you don’t know what any of that means - it’s not important for this portion of the course.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(oibiostat)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(famuss)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(famuss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ndrm.ch drm.ch    sex age      race height weight actn3.r577x    bmi
1      40     40 Female  27 Caucasian   65.0    199          CC 33.112
2      25      0   Male  36 Caucasian   71.7    189          CT 25.845
3      40      0 Female  24 Caucasian   65.0    134          CT 22.296
4     125      0 Female  40 Caucasian   68.0    171          CT 25.998
5      40     20 Female  32 Caucasian   61.0    118          CC 22.293
6      75      0 Female  24  Hispanic   62.2    120          CT 21.805</code></pre>
</div>
</div>
<p>The columns are a little difficult to understand, so here’s a brief overview.</p>
<table class="table">
<thead>
<tr class="header">
<th>variable</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sex</code></td>
<td>Biological sex of the patient</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>Age (years)</td>
</tr>
<tr class="odd">
<td><code>race</code></td>
<td>Self-reported race</td>
</tr>
<tr class="even">
<td><code>height</code></td>
<td>Subject’s height in inches</td>
</tr>
<tr class="odd">
<td><code>weight</code></td>
<td>Subject’s weight in pounds</td>
</tr>
<tr class="even">
<td><code>bmi</code></td>
<td>Subject’s body mass index (weight divided by height<span class="math inline">\(^2\)</span>)</td>
</tr>
<tr class="odd">
<td><code>actn3.r577x</code></td>
<td>I think it’s obvious what this column is</td>
</tr>
<tr class="even">
<td><code>drm.ch</code></td>
<td>Again, this is obvious.</td>
</tr>
<tr class="odd">
<td><code>ndrm.ch</code></td>
<td>No need to explain this one.</td>
</tr>
</tbody>
</table>
<p>Okay, so some of the columns need some explaining. The study was interested in whether a particular genotype affected the ability of subjects to build muscle. The genotype is at the genome position r557x in the ACTN3 gene, which is a fancy way of saying that the <code>actn3.r577x</code> tells us something about the subject’s genetic code. The genotype can be either <code>TT</code>, <code>TC</code>, <code>CT</code>, or <code>CC</code>, and the researchers believed that these genes determine how easily people build muscle.</p>
<p>The way the study was carried out is as follows. The researchers asked each subject to perform a test of strength using each arm. Subjects were then asked to follow a muscle strengthening exercise, but <em>only</em> on their non-dominant side (if they’re right handed, they were asked to strengthen their left arm). After the strengthening, they repeated the test of strength. The columns labelled <code>drm.ch</code> and <code>ndrm.ch</code> are the percentage change in their strength for their dominant arm and their non-dominant arm (the dominant arm was measured to see whether the patients gained or lost strength for reasons other than the prescribed strength training exercise).</p>
<ol type="1">
<li>Based on the R output, what type of variable is each column?</li>
<li>What counts as an individual in this study?
<ol type="a">
<li>Each person</li>
<li>Each pair of people</li>
<li>Each arm (two per person in the study)</li>
<li>Each column in the data</li>
</ol></li>
<li>Explain why either a bar chart or a pie chart would be appropriate for the <code>actn3.r577x</code> column. Be extremely precise.</li>
</ol>
</section>
<section id="ordered-and-unordered" class="level3">
<h3 class="anchored" data-anchor-id="ordered-and-unordered">Ordered and Unordered</h3>
<p>Whether the categorical variable is ordered or unordered affects the way we make the plot:</p>
<ul>
<li>Ordered: put the bars in order
<ul>
<li>For example, if we have data from 2020, 2021, and 2022, then we would have the bars in that order!</li>
</ul></li>
<li>Unordered: put it in an arbitrary order
<ul>
<li>Alternative: order according to largest to smallest.</li>
</ul></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> species) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Species"</span>, <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">"Unordered Categories"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats) <span class="co"># For rearranging "factors", aka. categorical variables</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_infreq</span>(species)) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Species"</span>, <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">"Unordered Categories, Ordered by Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The bar chart is the de-facto standard for categorical variables, whether binary or otherwise. For quantitative, variables, we need other options.</p>
</section>
<section id="quantitative-variables" class="level3">
<h3 class="anchored" data-anchor-id="quantitative-variables">Quantitative Variables</h3>
<p>Recall the distinction between discrete and continuous:</p>
<ul>
<li>Discrete (whole numbers)
<ul>
<li>Ex. Number of students in a classroom.</li>
</ul></li>
<li>Continuous (could be measured with more precision)
<ul>
<li>Ex. height</li>
</ul></li>
</ul>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Grey Area
</div>
</div>
<div class="callout-body-container callout-body">
<p>What type of variable is “dose level”, defined as either no dose, half dose, or full dose? They aren’t whole numbers, but we can’t measure them with greater precision!</p>
</div>
</div>
<div class="notes">
<p>Quantitative variables are split into discrete and continuous variables. Discrete variables are generally represented by whole numbers, for example, the number of students in a given classroom.</p>
<p>In contrast, continuous numbers could be anything! I like to think of them as numbers that could’ve been measured with more precision if we had better tools. For example, peoples Heights could be measured to infinite precision if we had perfect tools, whereas we don’t need better tools to measure the number of children in a family more precisely.</p>
<p>Of course, as with all things, there is a gray area here. Many studies will choose to give their subjects either no dose, a half dose or a full dose. These are obviously numbers and it is very likely that the response for a 0.75 dose is somewhere in between the half dose and the full dose. However, we chose these numbers and thus there are only three possible numbers. No amount of measuring is going to give us something other than a half dose (any deviation in administration of the dose can hopefully be ignored for the purpose of the study). In the definitions we’ve used it is neither a whole number, nor cannot be measured with higher precision. For the purposes of visualization, we might actually want to use a bar chart as if this were a categorical variable. If the dose had more categories and we expected the response to have a smooth trend across different dose levels, then we might use visualizations meant for discrete data. If the dose could have been any number between zero and one then we might use visualization meant for continuous data.</p>
</div>
</section>
<section id="plotting-quantitative-variables" class="level3">
<h3 class="anchored" data-anchor-id="plotting-quantitative-variables">Plotting Quantitative Variables</h3>
<p>Here are the lengths of sharks:</p>
<pre><code> 9.4 12.1 12.2 12.3 12.4 12.6 13.2 13.2 13.2 13.2 13.5
13.6 13.6 13.8 14.3 14.6 14.7 14.9 15.2 15.3 15.7 15.7
15.8 15.8 16.1 16.2 16.2 16.4 16.4 16.6 16.7 16.8 16.8
17.6 17.8 17.8 18.2 18.3 18.6 18.7 18.7 19.1 19.7 22.8</code></pre>
<ul>
<li>Even though we only know the data to one decimal point, we could have measured more precisely!
<ul>
<li>This is a continuous variable.</li>
<li>Note that there are ties in these data, and thus we could make bar charts with bars that are more than one unit tall. However, if we measured more precisely, these ties would go away.</li>
</ul></li>
<li>Can’t just draw a bar chart with all sharks that were 9.4, all that were 12.1, …</li>
</ul>
<div class="notes">
<p>How many we display this collection of shark lengths? It is clear that there are many different values that we could’ve gotten for the length and so we might not want to use something like a bar chart. Let’s try it anyway.</p>
</div>
</section>
<section id="quantitative-variables-as-a-bar-chart" class="level3">
<h3 class="anchored" data-anchor-id="quantitative-variables-as-a-bar-chart">Quantitative Variables as a Bar Chart</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span>  <span class="fu">c</span>(<span class="fl">9.4</span>, <span class="fl">12.1</span>, <span class="fl">12.2</span>, <span class="fl">12.3</span>, <span class="fl">12.4</span>, <span class="fl">12.6</span>, <span class="fl">13.2</span>, <span class="fl">13.2</span>, <span class="fl">13.2</span>, <span class="fl">13.2</span>, <span class="fl">13.5</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fl">13.6</span>, <span class="fl">13.6</span>, <span class="fl">13.8</span>, <span class="fl">14.3</span>, <span class="fl">14.6</span>, <span class="fl">14.7</span>, <span class="fl">14.9</span>, <span class="fl">15.2</span>, <span class="fl">15.3</span>, <span class="fl">15.7</span>, <span class="fl">15.7</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fl">15.8</span>, <span class="fl">15.8</span>, <span class="fl">16.1</span>, <span class="fl">16.2</span>, <span class="fl">16.2</span>, <span class="fl">16.4</span>, <span class="fl">16.4</span>, <span class="fl">16.6</span>, <span class="fl">16.7</span>, <span class="fl">16.8</span>, <span class="fl">16.8</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fl">17.6</span>, <span class="fl">17.8</span>, <span class="fl">17.8</span>, <span class="fl">18.2</span>, <span class="fl">18.3</span>, <span class="fl">18.6</span>, <span class="fl">18.7</span>, <span class="fl">18.7</span>, <span class="fl">19.1</span>, <span class="fl">19.7</span>, <span class="fl">22.8</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span> sharks) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="notes">
<p>This plot demonstrates why bar chart isn’t appropriate for these data. We can see that each data point essentially gets its own bar, and so the heights are no longer meaningful. The exception is that these data are rounded to one decimal place, and so some lengths end up in the same bar. Knowing that some of our data are rounded to the same value is not necessarily meaningful for any analyses that we might want to do. Instead, we would like a chart that shows us where most of the data are, and whether or not they are clear patterns in these data.</p>
</div>
</section>
<section id="histograms-put-observations-into-bins" class="level3">
<h3 class="anchored" data-anchor-id="histograms-put-observations-into-bins">Histograms: Put observations into bins</h3>
<p>The steps in building a histogram:</p>
<ol type="1">
<li>Choose the bins.
<ul>
<li>e.g.&nbsp;(0,10], (10,20], (20, 30], etc.
<ul>
<li>The notation (a, b] means that “a” is <em>not</em> included in the interval, but “b” is. We have no sharks that have a length of 0, but a shark with a recorded length of exactly 10 would be in the first bin, labelled (0, 10], not the second bin that is labelled (10, 20].</li>
</ul></li>
</ul></li>
<li>Count the number of obs. in each bin.</li>
<li>Draw a bar chart as if the bins are categories.
<ul>
<li>Bars should touch since there’s nothing in between.</li>
</ul></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Note that I've manually chosen the bin widths and centers.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> sharks) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="dv">2</span>, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="dv">0</span>, <span class="co"># Only need to specify the center of one bin</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Shark Length"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>In this histogram, the bins are (-1, 1], (1,3], (3,5]…</p>
<p>Notice how the y-axis is still “Counts” (like a bar chart).</p>
<div class="notes">
<p>Most of the time we will probably want to use a histogram to display quantitative, continuous data. A histogram is very much like putting continuous numbers into discrete bins, and then showing it as a bar chart. In this example, I chose bins from 1 to 3, then 3 to 5, then 5 to 7, and so on. For the bar on this histogram centred at a shark length of 12 we can see that there were five observations between 11 and 13. Note that the definitions of bins has a round bracket on the left side and the square bracket on the right side, this is to say that the left end point <em>is not</em> included but the right end point <em>is</em> included. This is just to account for cases where X may fall directly on the border between two bins, and we have to choose which bin. The actual bin we choose is arbitrary, kind of like driving in the left or the right. You will not be tested on whether you can remember which endpoint is inclusive.</p>
<p>From the plot, we can see that most of the sharks are around 16 feet in length with sun going down to 10 feet and some as long as around 22 feet. The plot has a nice bell shape.</p>
</div>
</section>
<section id="histograms-bin-width-matters" class="level3">
<h3 class="anchored" data-anchor-id="histograms-bin-width-matters">Histograms: Bin Width Matters!</h3>
<p>These histograms are showing the same data!</p>
<div class="columns">
<div class="column" style="width:48%;">
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> sharks) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="dv">2</span>, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="dv">0</span>, <span class="co"># Only need to specify the center of one bin</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Shark Length"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div><div class="column" style="width:48%;">
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> sharks) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">1.5</span>, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="fl">0.75</span>, <span class="co"># Only need to specify the center of one bin</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightgrey"</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Shark Length"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<div class="notes">
<p>In the previous graph, it looked like the distribution of sharks followed a nice bell-shaped curve. However, if we use bins that are 1.5 units wide we get a plot that looks fairly different. It still looks like most sharks are around 16 feet and some go down to 10 and some go as high is 22 or 23, But we see a large bar that covers 12 to 13.5.</p>
<p>With histograms the bins that you choose are extremely important. Most software have default values that are generally reasonable, But it’s always always always worth investigating other bins.</p>
<p>A simple version of the plot can be made as follows, where <code>ggplot</code> chooses the bins automatically. Note that this is rarely desireable, and you should almost always choose the bins yourself.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> sharks) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Below is an app to visualize the difference that the binwidth can make!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>shiny<span class="sc">::</span><span class="fu">runGitHub</span>(<span class="at">repo =</span> <span class="st">"DBecker7/DB7_TeachingApps"</span>, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">subdir =</span> <span class="st">"Apps/DensHist"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="describing-distributions" class="level3">
<h3 class="anchored" data-anchor-id="describing-distributions">Describing Distributions</h3>
<p>When you’re asked to comment on a histogram, always mention the following:</p>
<ul>
<li><strong>Shape</strong>: <strong>Unimodal</strong>/<strong>bimodal</strong> and <strong>skewness</strong>
<ul>
<li>Skewness: put a glob of peanut butter on toast, “skew” it to one side.</li>
</ul></li>
<li><strong>Center</strong>: midpoint (<strong>mean</strong>/<strong>median</strong>)
<ul>
<li><strong>Mode</strong> depends on the bin!</li>
<li>Skewness shows up in the relation between mean and median: “Mean less (than median) means left (skew).”</li>
</ul></li>
<li><strong>Spread</strong>: the <strong>range</strong>/<strong>variance</strong>/<strong>IQR</strong>
<ul>
<li>More on IQR later!</li>
</ul></li>
<li><strong>Outliers</strong>: points that don’t fit the shape
<ul>
<li>More on outliers when we cover IQR!</li>
</ul></li>
</ul>
<div class="notes">
<p>There are many shapes that a histogram can show. A distribution can be skewed (or “heavy-tailed”), which means that it looks like a bell curve but one side has a longer/thicker tail. We also want to know about several measures of the center of the distribution, as well as how spread out it is. Outliers are also something interesting to note; outliers are something that are <em>not</em> part of the shape (so you wouldn’t consider them when evaluating the skewness of a distribution).</p>
<p>Try drawing out each of these shapes/patterns!</p>
</div>
</section>
<section id="example-what-is-the-shape" class="level3">
<h3 class="anchored" data-anchor-id="example-what-is-the-shape">Example: What is the Shape?</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="notes">
<p>This represents a <strong>bimodal</strong> distribution because it has two peaks (the word “mode” can refer to the category with the most observations, but it can also refer to the top of a peak). This would be described as a bimodal distribution with centres around 190 and 215, ranges around 195 to 205 and 205 to 235, with both peaks being symmetric and without any outliers.</p>
</div>
</section>
<section id="example-what-is-the-shape-1" class="level3">
<h3 class="anchored" data-anchor-id="example-what-is-the-shape-1">Example: What is the Shape?</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="notes">
<p>This is the classic sort of gotcha question that I like to use. This is actually a bar chart that I modified so that the bars have no space in-between - the x-labels are categories, not ranges! It may look somewhat symmetric and unimodal without any outliers, but the x-labels are out of order. These numbers are just numerical encodings of species names - 1 refers to Adelie penguins, 2 refers to Chinstrap, and 3 refers to Gentoo. These numbers were applied alphabetically because there isn’t really a logical way to order these species: they’re unordered categories!</p>
<p>So, basically, it does not make sense to talk about shape in a bar graph where the labels could have been put in any order!</p>
</div>
</section>
<section id="purely-pedagogical-stem-and-leaf-plots." class="level3">
<h3 class="anchored" data-anchor-id="purely-pedagogical-stem-and-leaf-plots.">Purely Pedagogical: Stem-and-Leaf plots.</h3>
<p>Consider the data</p>
<pre><code>12, 43, 12, 32, 53, 66, 78, 25, 36, 12, 26,
34, 98, 39, 44, 23, 15, 67, 1,  4,  54, 21</code></pre>
<div class="columns">
<div class="column" style="width:20%;">

</div><div class="column" style="width:30%;">
<p><strong>Stem-and-Leaf</strong></p>
<pre><code>0  | 14
10 | 2225
20 | 1356
30 | 2469
40 | 34
50 | 34
60 | 67
70 | 8
80 |
90 | 8</code></pre>
</div><div class="column" style="width:50%;">
<p><strong>Sideways Histogram</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<div class="notes">
<p>This visualization technique is shown purely for pedagogical reasons. A stem and leaf plot is like a histogram where the bins are all powers of 10. It is displayed using the stem which is the first digit, and the leaf which is the second digit. For example, the number 78 has a 7 in the tens place (the tens place is the stem) and an 8 in the ones place (and we’re using the ones place as the leaf). In the stem and leaf plot, 78 goes on the stem labelled 70 and it gets a leaf of eight. Going the other way, we can see a stem labelled 90 and a leaf labelled eight which corresponds to the number 98. For the stem labelled zero we have the numbers one and four, for the stem label 10 we have the numbers 12, 12, 12, and 15.</p>
<p>Essentially, this is just a histogram. Instead of drawing a bar that corresponds to the number of observations in that bin, we are just listing the observations in that bin. Compare the stem and leaf plot to the sideways histogram on the right: in the first bin from 0 to 10 (not including 10) there are two numbers, one and four, and the length of the bin is two. For the stem label 20, we have the numbers 21, 23, 25 and 26, and this is displayed as a bar with length four in the histogram.</p>
<p>The main reason for showing this visualization technique is that it can be very useful for tests and quizzes, because it allows you to create a histogram without software. It also allows easy computation of the median since all of the leaves are in order. These are not used in practice because in practice you will have software to create histograms <em>and</em> find the median!<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
<p>Note that the shape of the distribution can be seen from the stem and leaf plot. It is a unimodal distribution that is right skewed and likely does not have any clear outliers (there is one point that appears to be separate from the others, but this might be due to bin choice).</p>
</div>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<ul>
<li><strong>Individuals</strong> are what we make measurements on
<ul>
<li>Can be pairs, dates, or people</li>
</ul></li>
<li><strong>Variables</strong> are what we measure
<ul>
<li>Can be derived from other measurements</li>
</ul></li>
<li>You will not be asked to do anything with pie charts in this course.</li>
<li><strong>Bar charts</strong> show counts of categories.
<ul>
<li>Can optionally sum to 1 (like a pie chart).</li>
</ul></li>
<li><strong>Histograms</strong> are like bar charts for binned data.
<ul>
<li><strong>Bins matter</strong>.</li>
<li>Must interpret <strong>shape</strong>.</li>
</ul></li>
</ul>
</section>
</section>
<section id="exercises" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="exercises"><span class="header-section-number">1.4</span> Exercises</h2>
<ol type="1">
<li>Which of the following plots would be appropriate for the <code>bmi</code> column?</li>
</ol>
<details>
<summary>
<strong>Bar chart</strong>
</summary>
<p>What do you think? Does the plot below give you any useful information about the data?</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</details>
<details>
<summary>
<strong>Pie Chart</strong>
</summary>
No.&nbsp;I’m not even going to try in this case.
</details>
<details>
<summary>
<strong>Histogram</strong>
</summary>
<p>Correct! The plot below tells us where most of the subjects’ BMI lie. We can see that most of the subjects are between 15 and 30, with a few between 30 and 35 and few above 35.</p>
<p>This is the whole reason we categorize variables as quantitative or categorical: knowing the type of the variable tells us which plots will give us useful information!</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</details>
<!---
## Participation Questions

### Q1

Which of the following visualizations would be *least* appropriate for **discrete** data?

1. Bar Chart
2. Histogram
3. Pie Chart
4. Stem-and-Leaf plot

### Q2

:::: {.columns}
::: {.column width="50%"}
\vspace{0.5cm}
What shape is the distribution on the right?

1. Symmetric
2. Left Skewed
3. Right Skewed

:::
::: {.column width="50%"}


::: {.cell}
::: {.cell-output-display}
![](L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-22-1.png){width=672}
:::
:::

:::
::::

### Q3

Age was collected as the number of days since birth. What kind of variable is this?

1. Ordered categorical
2. Unorded categorical
3. Discrete
4. Continuous

### Q4

Age was collected as 0-17, 18-25, 25-34, or 35+. What kind of variable is this?

1. Ordered categorical
2. Unorded categorical
3. Discrete
4. Continuous

### Q5

Age was collected as age in years, then rounded to the nearest 10. What kind of variable is the rounded value of age?

1. Ordered categorical
2. Unorded categorical
3. Discrete
4. Continuous

### Q6

:::: {.columns}
::: {.column width="50%"}
\vspace{1cm}


Approximately what proportion of the data is larger than 0? Note that there are 40 data points.



1. 50\%
2. 25\%
3. 75\%
4. 100\%

:::
::: {.column width="50%"}


::: {.cell}
::: {.cell-output-display}
![](L01-Intro_PicturingGraphs_files/figure-html/unnamed-chunk-23-1.png){width=480}
:::
:::


:::
::::

Answers: 334133
--->
<ol start="2" type="1">
<li><strong>Prescriptions of opioid pain relievers.</strong> Opioid pain relievers are prescribed at a higher rate in the United States than in any other nation, even though abuse of these medications can result in addiction and fatal overdoses. The CDC examined opioid pain reliever prescriptions in each state to find out how variable prescription rates are across the nation. Here are the 2012 state prescription rates, in number of prescriptions per 100 people, listed in increasing order:</li>
</ol>
<p><code>opiods &lt;- c(52.0, 57.0, 59.5, 61.6, 62.9, 65.1, 66.5, 67.4, 67.9, 69.6, 70.8, 71.2, 71.7, 72.4, 72.7, 72.8, 73.8, 74.3, 74.3, 74.7, 76.1, 77.3, 77.5, 79.4, 82.0, 82.4, 85.1, 85.6, 85.8, 88.2, 89.2, 89.6, 90.7, 90.8, 93.8, 94.1, 94.8, 96.6, 100.1, 101.8, 107.0, 109.1, 115.8, 118.0, 120.3, 127.8, 128.4, 137.6, 142.8, 142.9)</code></p>
<ol type="a">
<li>Make a histogram of the state opioid pain reliever prescription rates using classes of width 10 starting at 50.0 prescriptions per 100 people. e.g.&nbsp;(50, 60]. Do this by hand first, then using R.</li>
<li>Would you say that the distribution is single-peaked or multiple-peaked? Is it roughly symmetric or skewed?</li>
</ol>
<p>The Statistical Abstract of the United States, prepared by the Census Bureau, provides the number of single-organ transplants for the year 2010, by organ. The following two exercises are based on this table:</p>
<table class="table">
<thead>
<tr class="header">
<th>Disease</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Heart</td>
<td>2,333</td>
</tr>
<tr class="even">
<td>Lung</td>
<td>1,770</td>
</tr>
<tr class="odd">
<td>Liver</td>
<td>6,291</td>
</tr>
<tr class="even">
<td>Kidney</td>
<td>16,898</td>
</tr>
<tr class="odd">
<td>Pancreas</td>
<td>350</td>
</tr>
<tr class="even">
<td>Intestine</td>
<td>151</td>
</tr>
</tbody>
</table>
<ol start="3" type="1">
<li>The data on single-organ transplants can be displayed in</li>
</ol>
<ol type="a">
<li>a pie chart but not a bar graph.</li>
<li>a bar graph but not a pie chart.</li>
<li>either a pie chart or a bar graph.</li>
</ol>
<ol start="4" type="1">
<li>Kidney transplants represented what percent of single- organ transplants in 2010?</li>
</ol>
<ol type="a">
<li>Nearly 61%.</li>
<li>One-sixth (nearly 17%).</li>
<li>This percent cannot be calculated from the information provided in the table.</li>
</ol>
<p>See also: <a href="https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_OpenIntro_Statistics_(Diez_et_al)./01%3A_Introduction_to_Data/1.E%3A_Introduction_to_Data_(Exercises)">OpenIntro Textbook</a> problems relating to visualizations that we have learned, especially 1.30, 1.36, 1.37, 1.39, 1.40, 1.47.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>We’ll talk about what “explaining variance” means, along with exact ways to calculate it, in a later lecture.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>It is worth noting that there is also variance that isn’t information, and there’s information that we’ll never have access to. Variance is an opportunity to learn, but there’s almost always a limit to how much we can learn.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>A note on gender/sexuality/biology: penguins, especially Chinstrap and Gentoo penguins, don’t have particularly strong gender roles, and <a href="https://sites.tufts.edu/museumstudents/2021/02/22/whats-with-all-the-gay-penguins/">often form same-sex couples</a>. In this course, I will use the term “sex” to mean “biosex”, rather than “gender”, to indicate that we’re looking at morphological differences due to XX and XY chromosomes.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Possibly categorical if there are any penguins with chromosomal abnormalities.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>We may, however, know that factory workers have more exposure to a pathogen than those who work from home, but we would likely want to measure this directly rather than measuring it by proxy with occupation.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>We often encode on of the categories as 0 and the other as 1, but this is usually either clear (0 = no treatment, 1 = treatment) or completely arbitrary (0 = femala, 1 = male) and this arbitrariness is acknowledged. Neither of these cases affect the way we make plots or run analyses that are based on binary variables.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Not discreet.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>There are methods/visualizations that are specific to discrete variables, but they only apply in very specific circumstances and will not be taught in this course.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Of course, by “information”, I mean variance. If we don’t know the date that an observation was observed, we just have a collection of different numbers. If we see that there’s a pattern over time, we know a little more about why each number is different from the others!<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>It will still create a plot with the correct x and y axes, but won’t draw the bars.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>The “FAMUSS” acronym is a bit of a stretch, but just go with it.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>That software is R!<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./L02-Describing_Distributions_Numbers.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions with Numbers</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>